import { build } from 'esbuild';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trios-workflow-'));
const db=new DatabaseSync(':memory:');
for(const file of fs.readdirSync(root+'/drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync(root+'/drizzle/'+file,'utf8'));db.exec('PRAGMA foreign_keys=ON');
function prep(q){let args=[];return{bind(...a){args=a;return this},async first(){return db.prepare(q).get(...args)||null},async all(){return {results:db.prepare(q).all(...args)}},async run(){const out=db.prepare(q).run(...args);return {success:true,meta:{changes:out.changes}}},_q:q,_args:()=>args}}
const DB={prepare:prep,async batch(ps){db.exec('BEGIN');try{const out=[];for(const p of ps){if(/^\s*SELECT/i.test(p._q))out.push(await p.all());else out.push(await p.run())}db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
globalThis.__env={DB,OWNER_EMAILS:'owner@example.com',SITE_ORIGIN:'https://test.trios',BUCKET:{}};
globalThis.__headers=new Headers();process.env.OWNER_EMAILS='owner@example.com';process.env.SITE_ORIGIN='https://test.trios';
const stub={name:'platform-stubs',setup(b){
 b.onResolve({filter:/^(\.\/postgres-db|\.\/private-storage|\.\/supabase\/server|@\/lib\/supabase\/server)$/},a=>({path:a.path,namespace:'server-mock'}));
 b.onLoad({filter:/.*/,namespace:'server-mock'},a=>({contents:a.path.includes('postgres-db')?'export const database=globalThis.__env.DB':a.path.includes('private-storage')?'export const privateStorage=globalThis.__env.BUCKET':`export async function verifiedUser(){const h=globalThis.__headers;const id=h.get('oai-authenticated-user-id'),email=h.get('oai-authenticated-user-email');return id&&email?{id,email,email_confirmed_at:'verified',user_metadata:{full_name:h.get('oai-authenticated-user-full-name')||email}}:null} export function authConfigured(){return true}`,loader:'js'}));
b.onResolve({filter:/^cloudflare:workers$|^next\/headers$/},a=>({path:a.path,namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.__env':'export async function headers(){return globalThis.__headers}',loader:'js'}))}};
await build({entryPoints:[root+'/app/api/data/route.ts'],outfile:temp+'/trios-api-test.mjs',bundle:true,format:'esm',platform:'node',plugins:[stub],tsconfig:root+'/tsconfig.json'});
const api=await import(temp+'/trios-api-test.mjs');
function user(id,email){globalThis.__headers=new Headers(id?{'oai-authenticated-user-id':id,'oai-authenticated-user-email':email,'oai-authenticated-user-full-name':'Test Person'}:{})}
async function post(p,status=200){if(['payment','job'].includes(p.action)&&!p.commandId)p={...p,commandId:crypto.randomUUID()};if(p.action==='quote'&&!p.quoteVersion)p={...p,quoteVersion:db.prepare('SELECT updated_at FROM requests WHERE id=?').get(p.id)?.updated_at||'unknown'};const r=await api.POST(new Request('https://test.trios/api/data',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://test.trios'},body:JSON.stringify(p)}));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d}
async function get(mode='customer',status=200){const r=await api.GET(new Request('https://test.trios/api/data?mode='+mode));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d}
let checks=0;function passed(name){checks++;console.log('PASS '+name)}
user(null);assert.equal((await get()).user,null);await post({},401);passed('anonymous requests are blocked');
user('alice','alice@example.com');const id=crypto.randomUUID();const request={action:'request',id,name:'Alice <script>',email:'alice@example.com',phone:'7095551234',address:'15 Example Road',area:'St. John’s',postalCode:'A1A 1A1',services:['snow','lawn'],frequency:'Seasonal',details:{drivewaySize:'1',salt:true},consent:true};await post(request,201);await post(request);assert.equal((await get()).requests.length,1);assert.equal((await get()).requests[0].estimate,69900);passed('request is saved once and reference pricing is calculated on server');
await post({...request,id:crypto.randomUUID(),services:['electrical']},400);await post({action:'quote',id,total:1000,terms:'Seasonal work includes all agreed services.'},403);passed('unsupported services and customer admin actions are rejected');
await post({action:'property',label:'Home',address:'15 Example Road',area:'St. John’s',postalCode:'A1A 1A1',details:'Gate at left'});const property=(await get()).properties[0];
user('bob','bob@example.com');assert.equal((await get()).requests.length,0);await post({action:'property',id:property.id,label:'Hacked',address:'20 Another Street',area:'St. John’s',postalCode:'A1A 1A1'},404);await post({action:'request_action',id,status:'accepted'},404);await get('admin',403);passed('customer records and properties are isolated');
user('owner','owner@example.com');await post({action:'job',requestId:id,service:'snow',date:'2026-12-20',timeWindow:'9 AM–12 PM',crewId:null,priority:'Standard'},409);await post({action:'quote',id,total:1000,terms:'Seasonal services, including applicable tax. Arrival windows agreed before work. No roof work.'});passed('scheduling requires an accepted quote');
user('alice','alice@example.com');assert.equal((await get()).requests[0].status,'quoted');await post({action:'request_action',id,status:'accepted',quoteVersion:'stale'},409);await post({action:'request_action',id,status:'accepted',quoteVersion:(await get()).requests[0].updated_at});await post({action:'request_action',id,status:'cancelled'},409);passed('customer accepts the quote and accepted cancellation requires discussion');
user('owner','owner@example.com');await post({action:'crew',name:'Crew member',email:'crew@example.com',phone:'7095552234',area:'St. John’s'});let all=await get('admin');const crewId=all.crew[0].id;await post({action:'job',requestId:id,service:'lawn',date:'2027-05-10',timeWindow:'9 AM–12 PM',crewId,priority:'Standard',visits:3,interval:7});all=await get('admin');assert.equal(all.jobs.length,3);assert.equal(all.jobs[0].scheduled_date,'2027-05-24');passed('recurring visits persist with correct intervals');
user('crew','crew@example.com');const myJobs=(await get('crew')).jobs;assert.equal(myJobs.length,3);await get('admin',403);await post({action:'job_update',id:myJobs[0].id,version:0,status:'completed',notes:'Mowed and edged. Paths swept.',labourMinutes:45,cost:30,photos:[]});passed('assigned crew can complete work but cannot access owner records');
user('bob','bob@example.com');await post({action:'job_update',id:myJobs[0].id,version:0,status:'completed',notes:'',labourMinutes:0,cost:0,photos:[]},403);passed('unassigned users cannot alter jobs');
user('owner','owner@example.com');await post({action:'invoice',requestId:id,description:'Seasonal property care',amount:1000,tax:10,dueDate:'2026-12-15'},400);await post({action:'invoice',requestId:id,description:'Seasonal property care',amount:900,tax:100,dueDate:'2026-12-15'});all=await get('admin');const invoice=all.invoices[0];await post({action:'invoice',requestId:id,description:'Duplicate',amount:900,tax:100,dueDate:'2026-12-15'},409);passed('invoice totals match accepted quote and duplicate invoices are blocked');
user('alice','alice@example.com');await post({action:'payment',id:invoice.id,reference:'pretend'},403);user('owner','owner@example.com');await post({action:'payment',id:invoice.id,reference:'Verified bank transfer 123'});await post({action:'payment',id:invoice.id,reference:'duplicate'},409);passed('only owner can verify payment; duplicate recording is rejected');
user('alice','alice@example.com');assert.equal((await get()).invoices[0].status,'paid');await post({action:'message',subject:'Service question',body:'Could you confirm the next visit?'});user('owner','owner@example.com');all=await get('admin');await post({action:'reply',id:all.messages[0].id,reply:'Your next visit is scheduled in your account.'});user('alice','alice@example.com');assert.ok((await get()).messages[0].reply);passed('customer messages and staff replies persist');
user('owner','owner@example.com');await post({action:'crew_update',id:crewId,active:false});user('crew','crew@example.com');await get('crew',403);await post({action:'job_update',id:myJobs[1].id,version:0,status:'completed',notes:'',labourMinutes:0,cost:0,photos:[]},403);passed('deactivated crew lose job access');
const bad=await api.POST(new Request('https://test.trios/api/data',{method:'POST',headers:{Origin:'https://attacker.example','Content-Type':'application/json'},body:JSON.stringify(request)}));assert.equal(bad.status,403);passed('cross-origin mutations are rejected');
await build({entryPoints:[root+'/app/api/invoice/[id]/route.ts'],outfile:temp+'/trios-invoice-test.mjs',bundle:true,format:'esm',platform:'node',plugins:[stub],tsconfig:root+'/tsconfig.json'});
const invoiceApi=await import(temp+'/trios-invoice-test.mjs');
user('bob','bob@example.com');let inv=await invoiceApi.GET(new Request('https://test.trios/api/invoice/'+invoice.id),{params:Promise.resolve({id:invoice.id})});assert.equal(inv.status,404);
user('alice','alice@example.com');inv=await invoiceApi.GET(new Request('https://test.trios/api/invoice/'+invoice.id),{params:Promise.resolve({id:invoice.id})});assert.equal(inv.status,200);const html=await inv.text();assert.ok(html.includes('Alice &lt;script&gt;'));assert.ok(!html.includes('Alice <script>'));assert.ok(inv.headers.get('content-disposition').includes('attachment'));passed('invoice downloads enforce ownership and escape customer content');
const photoId=crypto.randomUUID();db.prepare('INSERT INTO uploads (id,user_id,name,mime,created_at) VALUES (?,?,?,?,?)').run(photoId,'alice','driveway.png','image/png',new Date().toISOString());
globalThis.__env.BUCKET.get=async()=>({body:new Uint8Array([137,80,78,71])});
await build({entryPoints:[root+'/app/api/files/[id]/route.ts'],outfile:temp+'/trios-files-test.mjs',bundle:true,format:'esm',platform:'node',plugins:[stub],tsconfig:root+'/tsconfig.json'});
const fileApi=await import(temp+'/trios-files-test.mjs');
user('bob','bob@example.com');let pic=await fileApi.GET(new Request('https://test.trios/api/files/'+photoId),{params:Promise.resolve({id:photoId})});assert.equal(pic.status,404);
user('alice','alice@example.com');pic=await fileApi.GET(new Request('https://test.trios/api/files/'+photoId),{params:Promise.resolve({id:photoId})});assert.equal(pic.status,200);assert.equal(pic.headers.get('cache-control'),'private, no-store');passed('property photo downloads remain private');
// Extended operating workflows.

user('owner','owner@example.com');await post({action:'crew_update',id:crewId,active:true});
const run={action:'job',commandId:crypto.randomUUID(),requestId:id,service:'snow',date:'2026-12-22',timeWindow:'Morning pass',crewId,priority:'Standard',visits:2,interval:1};
await post(run);const before=(await get('admin')).jobs.length;await post(run);assert.equal((await get('admin')).jobs.length,before);await post({...run,commandId:crypto.randomUUID()},409);await post({...run,commandId:crypto.randomUUID(),timeWindow:'Evening return pass',visits:1});passed('scheduling retries are idempotent; duplicate windows blocked; intentional snow return visits allowed');
await post({...run,commandId:crypto.randomUUID(),date:'2027-02-30'},400);await post({...run,commandId:crypto.randomUUID(),date:'2026-13-01'},400);await post({action:'quote',id,total:1.004,terms:'A scope with fractional cents.'},400);passed('invalid calendar dates and fractional-cent amounts rejected');
const done=(await get('admin')).jobs.find(j=>j.status==='completed');const completedAt=done.completed_at;
await post({action:'job_update',id:done.id,version:done.version,status:'scheduled',notes:'reopen',labourMinutes:45,cost:30},409);
await post({action:'job_update',id:done.id,version:done.version,status:'completed',notes:'Corrected completion note.',labourMinutes:45,cost:30});
assert.equal((await get('admin')).jobs.find(j=>j.id===done.id).completed_at,completedAt);
await post({action:'job_update',id:done.id,version:done.version,status:'completed',notes:'Stale save',labourMinutes:45,cost:30},409);passed('closed jobs cannot regress, first completion time is preserved and stale edits fail');
const pending=(await get('admin')).jobs.find(j=>j.status==='scheduled');
await post({action:'assign_job',id:pending.id,version:pending.version,crewId:null});await post({action:'reschedule',id:pending.id,version:pending.version,date:'2027-06-01',timeWindow:'Morning',reason:'Rain delay'},409);passed('assignment and rescheduling enforce optimistic concurrency');
const intake={action:'intake',id:crypto.randomUUID(),name:'Phone Customer',email:'phone@example.com',phone:'7095557766',address:'9 Harbour Street',area:'St. John’s',postalCode:'A1A 2B2',services:['snow'],frequency:'Seasonal',source:'Phone',notes:'Customer requests a clear walkway.',consent:true};
await post(intake,201);await post(intake);let offline=(await get('admin')).requests.find(r=>r.id===intake.id);assert.ok(offline.user_id.startsWith('contact:'));assert.notEqual(offline.user_id,'owner');
await post({action:'quote',id:intake.id,total:1000,terms:'Seasonal snow visits. All applicable taxes included. Response window confirmed with the customer.'});offline=(await get('admin')).requests.find(r=>r.id===intake.id);
const previousQuoteVersion=offline.updated_at;await new Promise(resolve=>setTimeout(resolve,2));await post({action:'quote',id:intake.id,quoteVersion:previousQuoteVersion,total:1000,terms:offline.quote_terms+' Confirmed property access.'});await post({action:'quote',id:intake.id,quoteVersion:previousQuoteVersion,total:900,terms:'This stale edit must not replace the current quote.'},409);offline=(await get('admin')).requests.find(r=>r.id===intake.id);passed('stale quote editors cannot overwrite a newer customer quote');
await post({action:'offline_approval',id:intake.id,quoteVersion:'old',signer:'Phone Customer',method:'Phone',evidence:'Approved by phone on the recorded date.',confirmed:true},409);
await post({action:'offline_approval',id:intake.id,quoteVersion:offline.updated_at,signer:'Phone Customer',method:'Phone',evidence:'Approved by phone on September 6. Agreed exact scope and total.',confirmed:true});
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM approvals WHERE request_id=?').get(intake.id).n,1);passed('offline intake has separate customer identity and a versioned approval evidence record');
user('intruder','intruder@example.com');assert.equal((await get()).requests.length,0);await post({...intake,id:crypto.randomUUID()},403);
user('phone-user','phone@example.com');const phoneData=await get();assert.equal(phoneData.requests[0].id,intake.id);assert.equal(phoneData.requests[0].user_id,'phone-user');assert.equal(phoneData.requests[0].status,'accepted');passed('only the matching trusted sign-in email claims offline customer records');
user('owner','owner@example.com');await post({action:'invoice',requestId:intake.id,description:'Winter snow care',amount:900,tax:100,dueDate:'2026-12-15'});const depositInvoice=(await get('admin')).invoices.find(i=>i.request_id===intake.id);
const deposit={action:'payment',commandId:crypto.randomUUID(),id:depositInvoice.id,amount:300,method:'Cash',receivedDate:'2026-09-06',reference:'Cash receipt 007'};await post(deposit);await post(deposit);let ledger=(await get('admin'));assert.equal(ledger.invoices.find(i=>i.id===depositInvoice.id).status,'partial');assert.equal(ledger.invoices.find(i=>i.id===depositInvoice.id).paid_cents,30000);assert.equal(ledger.payments.filter(p=>p.invoice_id===depositInvoice.id).length,1);
await post({...deposit,commandId:crypto.randomUUID(),amount:701},409);await post({...deposit,commandId:crypto.randomUUID(),amount:700,reference:'Final bank transfer 008',method:'E-transfer'});assert.equal((await get('admin')).invoices.find(i=>i.id===depositInvoice.id).status,'paid');passed('deposits, idempotent payment records, balance limits and final payment reconcile');
await post({action:'settings',dailyCapacity:1,invoiceDays:14,quoteTerms:'Default agreed scope for assessment.',paymentInstructions:'Call Trios for bank recipient details.'});assert.equal((await get('admin')).settings.invoiceDays,14);
const onSameDay=(await get('admin')).jobs.filter(j=>j.scheduled_date==='2026-12-22'&&j.status==='scheduled');await post({action:'dispatch',commandId:crypto.randomUUID(),crewId,jobs:onSameDay.map(j=>({id:j.id,version:j.version}))},409);
await post({action:'settings',dailyCapacity:12,invoiceDays:14,quoteTerms:'Default agreed scope for assessment.',paymentInstructions:'Call Trios for bank recipient details.'});await post({action:'dispatch',commandId:crypto.randomUUID(),crewId,jobs:onSameDay.map(j=>({id:j.id,version:j.version}))});passed('operating settings persist and bulk crew assignment respects daily capacity');
user('phone-user','phone@example.com');assert.equal((await get()).settings.paymentInstructions,'Call Trios for bank recipient details.');await post({action:'settings',dailyCapacity:100,invoiceDays:1,quoteTerms:'',paymentInstructions:'Attacker bank'},403);
await build({entryPoints:[root+'/app/api/quote/[id]/route.ts',root+'/app/api/calendar/route.ts',root+'/app/api/export/route.ts'],outdir:temp+'/exports',outbase:root+'/app/api',bundle:true,format:'esm',outExtension:{'.js':'.mjs'},platform:'node',plugins:[stub],tsconfig:root+'/tsconfig.json'});
const quoteApi=await import(temp+'/exports/quote/[id]/route.mjs');const calendarApi=await import(temp+'/exports/calendar/route.mjs');const exportApi=await import(temp+'/exports/export/route.mjs');
const ownQuote=await quoteApi.GET(new Request('https://test.trios/api/quote/'+intake.id),{params:Promise.resolve({id:intake.id})});assert.equal(ownQuote.status,200);assert.ok((await ownQuote.text()).includes('Phone Customer'));
user('bob','bob@example.com');assert.equal((await quoteApi.GET(new Request('https://test.trios/api/quote/'+intake.id),{params:Promise.resolve({id:intake.id})})).status,404);assert.equal((await calendarApi.GET(new Request('https://test.trios/api/calendar?mode=admin'))).status,403);assert.equal((await exportApi.GET(new Request('https://test.trios/api/export?type=customers'))).status,403);
user('alice','alice@example.com');const calendar=await calendarApi.GET(new Request('https://test.trios/api/calendar'));const ics=await calendar.text();assert.ok(ics.includes('BEGIN:VCALENDAR'));assert.ok(ics.includes('Morning pass'));assert.ok(!ics.includes('9 Harbour Street'));
user('owner','owner@example.com');const csv=await exportApi.GET(new Request('https://test.trios/api/export?type=invoices'));assert.ok((await csv.text()).includes('Balance CAD'));passed('quote downloads, calendar exports and business CSVs enforce roles and ownership');
const badJson=await api.POST(new Request('https://test.trios/api/data',{method:'POST',headers:{Origin:'https://test.trios'},body:'not json'}));assert.equal(badJson.status,400);
const huge=await api.POST(new Request('https://test.trios/api/data',{method:'POST',headers:{Origin:'https://test.trios'},body:JSON.stringify({action:'message',body:'x'.repeat(60000)})}));assert.equal(huge.status,413);passed('malformed and oversized request bodies fail safely');

user('owner','owner@example.com');const direct={...intake,id:crypto.randomUUID(),email:'direct@example.com',name:'Direct Customer'};await post(direct,201);await post({action:'quote',id:direct.id,total:0,terms:'A complimentary property visit. No payment is required.'});const directQuote=(await get('admin')).requests.find(r=>r.id===direct.id);await post({action:'offline_approval',id:direct.id,quoteVersion:directQuote.updated_at,signer:'Direct Customer',method:'Email',evidence:'Customer approved the complimentary assessment by email.',confirmed:true});await post({action:'invoice',requestId:direct.id,description:'Complimentary assessment',amount:0,tax:0,dueDate:'2026-12-15'});const freeInvoice=(await get('admin')).invoices.find(i=>i.request_id===direct.id);assert.equal(freeInvoice.status,'paid');assert.equal((await get('admin')).payments.filter(p=>p.invoice_id===freeInvoice.id).length,0);
user('direct-user','direct@example.com');assert.equal((await quoteApi.GET(new Request('https://test.trios/api/quote/'+direct.id),{params:Promise.resolve({id:direct.id})})).status,200);assert.equal(db.prepare('SELECT user_id FROM requests WHERE id=?').get(direct.id).user_id,'direct-user');passed('zero-balance invoices settle without fabricated payments and direct quote downloads link the authenticated customer');
user('owner','owner@example.com');await post({action:'settings',dailyCapacity:1,invoiceDays:14,quoteTerms:'',paymentInstructions:'Contact Trios.'});await post({...run,commandId:crypto.randomUUID(),date:'2026-12-22',timeWindow:'Extra conflicting pass',visits:1},409);
const missingKey=await api.POST(new Request('https://test.trios/api/data',{method:'POST',headers:{Origin:'https://test.trios'},body:JSON.stringify({action:'payment',id:depositInvoice.id,amount:1,reference:'Missing key'})}));assert.equal(missingKey.status,400);passed('individual schedules also enforce capacity and payment commands require idempotency keys');
user(null);await get('admin',401);await get('crew',401);
user('alice','alice@example.com');await get('crew',403);await get('admin&role=admin',403);
const scoped=await get();assert.ok(scoped.jobs.length);assert.ok(scoped.payments.length);
for(const job of scoped.jobs)for(const key of ['cost_cents','labour_minutes','crew_id','user_id','version'])assert.ok(!(key in job),key);
for(const payment of scoped.payments)assert.ok(!('recorded_by' in payment));
assert.deepEqual(scoped.crew,[]);assert.deepEqual(scoped.equipment,[]);assert.deepEqual(scoped.contacts,[]);assert.ok(!('dailyCapacity' in scoped.settings));
user('owner','owner@example.com');const privateRecords=await get('admin');assert.ok('cost_cents' in privateRecords.jobs[0]);assert.ok('recorded_by' in privateRecords.payments[0]);
passed('staff API modes require roles and customer payloads omit internal costs and staff records');
console.log(`${checks} workflow and authorization checks passed. Test records exist only in the in-memory test database.`);

fs.rmSync(temp,{recursive:true,force:true});
