'use client';

import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Snowflake, CalendarDays, MapPin, ClipboardCheck, House, Phone, Check, SlidersHorizontal } from 'lucide-react';
import { SERVICES, CONTACT, SEASON } from '@/lib/catalog';
import { Pick, ServiceIcon } from './shared';
import { MovingFeatureBand } from './moving-public';
import { SeasonalExplorer, PublicFAQ, CareProcess } from './public-care-tools';
import { CinematicHero } from './cinematic-hero';

export function Home() {
  const [service, setService] = useState('snow');
  const [postal, setPostal] = useState('');
  return <div className="public-upgrade public-home">
    <CinematicHero />
    <section className="cinematic-request-band" aria-label="Start a property care request">
      <div className="container"><form className="public-quote-start" action="/book"><div className="public-quote-intro"><House size={28} /><div><strong>Good care starts here.</strong><span>Tell us what your property needs.</span></div></div><div className="field"><label htmlFor="home-service">Choose your first service</label><Pick id="home-service" value={service} onChange={setService} label="Service" options={SERVICES.map(s => ({ value: s.id, label: s.name }))} /><input type="hidden" name="service" value={service} /></div><label htmlFor="home-postal">Postal code <span>(optional)</span><input id="home-postal" name="postal" autoComplete="postal-code" autoCapitalize="characters" spellCheck={false} placeholder="A1A 1A1" value={postal} onChange={e => setPostal(e.target.value.toUpperCase())} maxLength={7} pattern="[ABCEGHJ-NPRSTVXYabceghj-nprstvxy][0-9][ABCEGHJ-NPRSTVWXYZabceghj-nprstvwxyz][ -]?[0-9][ABCEGHJ-NPRSTVWXYZabceghj-nprstvwxyz][0-9]" /></label><button className="button" type="submit">Start my request <ArrowRight size={21} /></button></form></div>
    </section>
    <div className="container public-value-strip"><span><MapPin size={23} />Locally focused</span><span><CalendarDays size={23} />One-time or seasonal</span><span><ClipboardCheck size={23} />Scope agreed first</span><span><House size={23} />Your home & next move</span></div>
    <section className="container public-section"><div className="public-section-heading"><div><div className="eyebrow">MORE ROOM FOR EVERYDAY LIFE</div><h2>The essentials.<br /><span>All in good order.</span></h2></div><div><p>Choose the help you need now. Build on it as the seasons change.</p><a className="text-link" href="/services">Find & compare services <ArrowUpRight size={20} /></a></div></div><div className="public-feature-grid">{SERVICES.filter(s => ['snow', 'lawn', 'moving'].includes(s.id)).map(s => <article className="public-feature-service" key={s.id}><a href={'/services/' + s.id} className="public-feature-photo"><img src={s.image} width={1536} height={1024} loading="lazy" alt={s.id === 'moving' ? 'Boxes packed and ready for a home move' : s.id === 'snow' ? 'Snow surrounding a residential driveway' : 'A green lawn outside a coastal home'} /><span className="public-feature-category"><ServiceIcon name={s.icon} />{s.category} care</span></a><div className="public-feature-body"><h3><a href={'/services/' + s.id}>{s.name}</a></h3><p>{s.summary}</p><div><span>{s.price}{s.unit && <small> {s.unit}</small>}</span><a href={'/services/' + s.id} aria-label={'Learn about ' + s.name}><ArrowUpRight size={23} /></a></div></div></article>)}</div><div className="moving-home-planner"><SlidersHorizontal size={30} /><div><h3>One property plan. Your priorities.</h3><p>Combine moving, lawn care, seasonal work and cleaning in one quote request.</p></div><a className="button" href="/planner">Build my service mix <ArrowUpRight size={21} /></a></div><div className="public-winter-note"><Snowflake size={24} /><div><strong>Planning ahead for winter?</strong><span>{SEASON}. Explore your driveway options and available additions.</span></div><a href="/plans#winter-estimate" className="text-link">Compare winter options <ArrowRight size={20} /></a></div></section>
    <section className="container public-section public-no-top"><MovingFeatureBand /></section>
    <section className="public-season-background"><div className="container public-section"><SeasonalExplorer /></div></section>
    <section className="container public-section"><CareProcess /></section>
    <section className="public-account-band"><div className="container public-account-grid"><div><div className="eyebrow">LESS CHASING. MORE CLARITY.</div><h2>Your property story,<br />kept together.</h2><p>Keep the details that matter close at hand: your service requests, moving inventory, accepted quotes, scheduled care and visit records.</p><a className="button lime" href="/portal">Open my property account <ArrowUpRight size={22} /></a></div><div className="public-account-list">{[[House, 'Property details', 'Address, access needs and the notes you choose to share.'], [ClipboardCheck, 'Quotes & agreements', 'Review scope and pricing before accepting work.'], [CalendarDays, 'Visits & records', 'Follow agreed visits, completion notes and invoices.']].map(([Icon, title, copy]) => { const ItemIcon = Icon as typeof House; return <div key={String(title)}><ItemIcon size={25} /><span><strong>{String(title)}</strong><span>{String(copy)}</span></span><Check size={20} /></div>; })}</div></div></section>
    <section className="container public-section"><PublicFAQ searchable={false} /></section>
    <section className="container public-human-help"><div><Phone size={27} /><div><h3>Prefer to talk it through?</h3><p>Speak with Trios about your property and the services you have in mind.</p></div></div><a className="button outline" href={'tel:' + CONTACT.tel}>{CONTACT.phone}<ArrowUpRight size={21} /></a></section>
  </div>;
}
