'use client';

import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Box, Check, CheckCircle2, ClipboardCheck, ClipboardList, Download, House, MapPin, PackageCheck, Phone, Plus, SlidersHorizontal, Truck } from 'lucide-react';
import { MOVING_TIERS, MOVING_ADDONS } from '@/lib/moving';
import { CONTACT } from '@/lib/catalog';

type TierId = 'help' | 'essentials' | 'pack' | 'complete';
const tierIcons = { help: Box, essentials: Truck, pack: PackageCheck, complete: House };
const quoteUrl = (tier: string) => `/book?service=moving&tier=${tier}`;
const moveTypeNames: Record<string, string> = { home: 'Home move', apartment: 'Apartment / condo', student: 'Student move', office: 'Office / small business', storage: 'Storage move' };
const situations = [
  { id: 'home', name: 'House & townhouse', summary: 'Room-by-room planning for the belongings and access that shape your move.', detail: 'List furniture, boxed belongings, stairs, outdoor access and any pieces that need disassembly. Separate the items staying behind.' },
  { id: 'apartment', name: 'Apartment & condo', summary: 'Small spaces can have big access details. Plan them together.', detail: 'Share floor numbers, elevator dimensions and reservations, loading arrangements, building hours and how far items must be carried.' },
  { id: 'student', name: 'Student & small move', summary: 'A room, a few pieces or a first place. Start with the actual inventory.', detail: 'Describe the items, shared-building access and your available dates. Labour-only help can be requested when you arrange suitable transport.' },
  { id: 'office', name: 'Office & workspace', summary: 'A structured request for a small business relocation.', detail: 'Map desks and furniture to the new layout. Share phased access needs and any sensitive equipment. IT disconnects, reconnection and data handling need separate arrangements.' },
  { id: 'storage', name: 'Storage & downsizing', summary: 'Plan what goes where, with an inventory that everyone can follow.', detail: 'Identify the primary destination and tell Trios about extra stops for assessment. Storage hire, disposal, donation drop-offs and specialist handling are separate scope items.' },
];
const checklistGroups = [
  { title: 'When you start planning', tasks: ['List the items moving and their destination rooms.', 'Measure large furniture, doorways, stair turns and elevator openings.', 'Share both addresses and the dates you can work with.'] },
  { title: 'Before the agreed move', tasks: ['Review the written scope, price, timing, cancellation terms and any coverage information.', 'Arrange building access, elevator reservations and permitted loading space.', 'Label boxes by room and flag fragile, heavy or unusual items.'] },
  { title: 'On moving day', tasks: ['Keep medication, valuables, documents and daily essentials with you.', 'Walk through the agreed inventory and note existing item conditions.', 'Keep paths clear and arrange for children and pets to stay out of work areas.'] },
  { title: 'At the destination', tasks: ['Confirm where furniture and boxes should be placed.', 'Check the inventory and note any missing items or concerns with the crew.', 'Review the completion record and keep your agreement and invoice together.'] },
];
const comparison = [
  ['Inventory & access review', 'Included in assessment', 'Included in assessment', 'Included in assessment', 'Included in assessment'],
  ['Loading / unloading labour', 'Agreed tasks', 'Included in proposed scope', 'Included in proposed scope', 'Included in proposed scope'],
  ['Transport', 'Arranged by you', 'Reviewed in quote', 'Reviewed in quote', 'Reviewed in quote'],
  ['Packing assistance', 'Optional addition', 'Optional addition', 'Agreed rooms / items', 'Agreed rooms / items'],
  ['Unpacking & placement', 'Optional addition', 'Basic agreed placement', 'Basic agreed placement', 'Agreed unpacking / setup'],
  ['Property-care coordination', 'Request separately', 'Request separately', 'Request separately', 'Choose optional care services'],
  ['Materials, extra stops & special items', 'Itemized separately', 'Itemized separately', 'Itemized separately', 'Itemized separately'],
];
const movingFaqs = [
  ['Which tier should I choose?', 'Start with Moving Help for labour when you arrange transport. Local Essentials adds transport assessment. Pack & Move adds an agreed packing scope. Complete Transition adds agreed unpacking and setup, with property services available as separate additions. The tier finder helps narrow the starting point; your written quote defines the final service.'],
  ['Can I get a price before providing an inventory?', 'Every moving request is assessed. Item count and size, packing, loading distance, stairs, elevators, travel, crew needs and additional stops affect the work. Start with the inventory you know and mark uncertain details for review. This site does not calculate a binding moving price.'],
  ['Is choosing a date a reservation?', 'No. Your requested date and any flexibility are planning information. Trios must confirm scope, suitable resources, service timing and payment arrangements before a move is booked. Check the latest agreement and account updates.'],
  ['Does every tier include a moving truck?', 'Moving Help is labour-only; you arrange suitable transport. Transport for other tiers is assessed and included only when confirmed in writing. Vehicle size, crew and transport arrangements are not reserved by this website.'],
  ['What about pianos, safes, oversized items or appliances?', 'List unusual, exceptionally heavy, fragile or high-value items before requesting a quote. These may need specialist handling, equipment or a referral. Hoisting, hazardous materials, utility connections and specialist installation are outside the standard moving scope. Do not assume a listed item has been accepted.'],
  ['Can you pack everything or help with only one room?', 'You can request a full agreed packing scope or selected rooms and items. Tell Trios what you will pack yourself, whether materials are needed and what requires special assessment. Materials and the final packing scope are itemized in the quote.'],
  ['Can I combine a move with cleaning or lawn care?', 'Yes. Include home cleaning, lawn care or seasonal services in the same request. Complete Transition provides a starting point for coordinating those needs, but every additional service has its own agreed scope and price. Moving tiers do not automatically include cleaning or waste disposal.'],
  ['What if the inventory or access changes?', 'Tell Trios before the move through your account or by phone. Additional items, extra stops, changed access or packing requirements may need a revised scope and written approval. Keep your original request, accepted quote and approved changes together.'],
  ['How do I prepare for a winter move?', 'Share driveway slope, outdoor steps, expected loading space and possible weather exposure at both addresses. Request any snow or ice services separately. Weather and access conditions may require changes to the agreed plan; timing is confirmed directly.'],
  ['Where are moving requests considered?', 'Start with St. John’s and nearby communities. Both origin and destination, any extra stops and the travel involved need assessment. Long-distance, ferry and out-of-province work are not automatically available. Contact Trios before relying on those arrangements.'],
];

export function MovingFeatureBand({ compact = false }: { compact?: boolean }) {
  return <section className={'moving-feature-band' + (compact ? ' moving-feature-compact' : '')} aria-label="Moving services"><div className="moving-feature-image"><img src="/moving-hero.webp" width={1536} height={1024} loading="lazy" alt="Packed moving boxes and a plant in a bright home" /><span><Truck size={23} />A new chapter, thoughtfully planned.</span></div><div className="moving-feature-copy"><div className="eyebrow">NEW TO TRIOS · MOVING SERVICES</div><h2>Care for your home.<br /><span>Help with what’s next.</span></h2><p>From an extra pair of hands to packing, moving and settling in. Explore four levels of help, then build a request around your belongings, your addresses and your priorities.</p><div className="moving-feature-tags"><span>Labour-only help</span><span>Local moves</span><span>Packing & settling in</span></div><a className="button" href="/moving">Explore moving services <ArrowUpRight size={22} /></a><a className="text-link" href="/moving#moving-tier-finder">Find my moving tier <ArrowRight size={20} /></a></div></section>;
}

function TierFinder() {
  const [transport, setTransport] = useState('review');
  const [packing, setPacking] = useState('self');
  const [settling, setSettling] = useState('placement');
  const [situation, setSituation] = useState('home');
  const tierId: TierId = settling === 'unpack' ? 'complete' : packing === 'help' ? 'pack' : transport === 'own' ? 'help' : 'essentials';
  const tier = MOVING_TIERS.find(item => item.id === tierId)!;
  const finderQuery = new URLSearchParams({ service: 'moving', tier: tierId, moveType: moveTypeNames[situation], transport: transport === 'own' ? 'Customer arranged' : 'Request transport' });
  const transportNote = transport === 'own' && tierId !== 'help' ? 'You already have transport. Ask Trios to quote the packing or unpacking labour you need and exclude transport from the final scope.' : tierId === 'help' ? 'You arrange transport. Tell Trios whether you need loading, unloading or on-site moving help.' : 'Transport, vehicle suitability and the route need a review before confirmation.';
  return <section id="moving-tier-finder" className="moving-finder" aria-labelledby="moving-finder-title"><div className="moving-finder-form"><div className="eyebrow"><SlidersHorizontal size={23} />YOUR MOVING STARTING POINT</div><h2 id="moving-finder-title">What would make<br />your move easier?</h2><p>Four quick choices shape a suggested tier. Adjust the details in your quote request.</p><div className="moving-finder-fields"><label>What are you moving?<select value={situation} onChange={e => setSituation(e.target.value)}>{situations.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Transport arrangements<select value={transport} onChange={e => setTransport(e.target.value)}><option value="review">Include transport in the assessment</option><option value="own">I will arrange suitable transport</option></select></label><label>Packing support<select value={packing} onChange={e => setPacking(e.target.value)}><option value="self">I will pack my belongings</option><option value="help">I would like packing assistance</option></select></label><label>At the destination<select value={settling} onChange={e => setSettling(e.target.value)}><option value="placement">Place agreed furniture and boxes</option><option value="unpack">Help unpack and settle in</option></select></label></div></div><aside className="moving-finder-result" aria-live="polite"><span className="moving-result-label">SUGGESTED STARTING TIER</span><span className="moving-result-icon">{tierId === 'help' ? <Box size={34} /> : tierId === 'essentials' ? <Truck size={34} /> : tierId === 'pack' ? <PackageCheck size={34} /> : <House size={34} />}</span><h3>{tier.name}</h3><p>{tier.summary}</p><ul>{tier.includes.slice(0, 3).map(item => <li key={item}><Check size={19} /><span>{item}</span></li>)}</ul><p className="moving-result-note">{transportNote}</p><a className="button lime full" href={'/book?' + finderQuery.toString()}>Build this moving request <ArrowRight size={21} /></a><a href={'/moving/' + tierId} className="moving-result-more">See the full tier details <ArrowUpRight size={19} /></a><span className="moving-result-foot">Guided suggestion. Scope, price and availability require review.</span></aside></section>;
}

function MovingChecklist() {
  const [checked, setChecked] = useState<string[]>([]);
  const [status, setStatus] = useState('');
  const count = checklistGroups.reduce((total, group) => total + group.tasks.length, 0);
  function download() {
    const text = `TRIOS · MOVING PREPARATION CHECKLIST\n\n${checklistGroups.map(group => `${group.title.toUpperCase()}\n${group.tasks.map(task => `[${checked.includes(task) ? 'x' : ' '}] ${task}`).join('\n')}`).join('\n\n')}\n\nThis is a personal preparation checklist, not a booking or crew completion record. Your accepted quote defines the work.\n${CONTACT.phone} · ${CONTACT.email}`;
    const href = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' }));
    const link = document.createElement('a'); link.href = href; link.download = 'trios-moving-preparation.txt'; link.click(); URL.revokeObjectURL(href); setStatus('Your preparation checklist was downloaded.');
  }
  return <section className="moving-preparation" id="moving-preparation"><div className="moving-section-heading"><div><div className="eyebrow">LESS TO REMEMBER. MORE ROOM TO BREATHE.</div><h2>Your moving<br /><span>preparation list.</span></h2></div><p>Tick off the details as you prepare, then download a copy. These ticks stay on this page and are not sent to the crew.</p></div><div className="moving-prep-progress"><div><ClipboardCheck size={25} /><strong>{checked.length} of {count} steps checked</strong></div><progress max={count} value={checked.length} aria-label="Moving preparation progress" /><button type="button" onClick={download}><Download size={20} />Download checklist</button></div><div className="moving-checklist-grid">{checklistGroups.map((group, index) => <article key={group.title}><span className="moving-step-number">0{index + 1}</span><h3>{group.title}</h3>{group.tasks.map(task => <label key={task}><input type="checkbox" checked={checked.includes(task)} onChange={() => setChecked(previous => previous.includes(task) ? previous.filter(item => item !== task) : [...previous, task])} /><span>{task}</span></label>)}</article>)}</div><p role="status">{status}</p></section>;
}

export function MovingPublic({ tierId }: { tierId?: string }) {
  const [situation, setSituation] = useState('home');
  const [faqQuery, setFaqQuery] = useState('');
  const selectedTier = MOVING_TIERS.find(item => item.id === tierId);
  const visibleFaqs = movingFaqs.filter(item => item.join(' ').toLowerCase().includes(faqQuery.trim().toLowerCase()));
  const currentSituation = situations.find(item => item.id === situation)!;
  return <div className="moving-public public-upgrade"><section className="moving-hero"><div className="container moving-hero-grid"><div className="moving-hero-copy"><div className="eyebrow"><Truck size={24} />MOVING SERVICES · ST. JOHN’S</div>{selectedTier ? <><a className="moving-back-link" href="/moving">All moving tiers <ArrowUpRight size={18} /></a><h1>{selectedTier.name}.<br /><em>A plan for<br />your next chapter.</em></h1><p>{selectedTier.summary}</p></> : <><h1>New place.<br />Fresh start.<br /><em>We’ll help you<br />get there.</em></h1><p>Moving help built around your life. From loading a few things to packing and settling in, bring every detail into one thoughtful plan.</p></>}<div className="moving-hero-actions"><a className="button lime" href={selectedTier ? quoteUrl(selectedTier.id) : '/book?service=moving'}>Plan my move <ArrowUpRight size={23} /></a><a className="moving-light-link" href="#moving-tiers">Compare the four tiers <ArrowRight size={21} /></a></div><div className="moving-hero-note"><ClipboardCheck size={22} /><span>Inventory first. Written scope. A quote for your move.</span></div></div><div className="moving-hero-visual"><img src="/moving-hero.webp" width={1536} height={1024} fetchPriority="high" alt="Moving boxes and a houseplant ready for a new chapter in a bright home" /><div className="moving-image-caption"><span>FROM YOUR FIRST BOX</span><strong>To feeling<br />at home.</strong><span className="moving-caption-arrow"><ArrowUpRight size={28} /></span></div><div className="moving-hero-tag"><Box size={25} /><span><strong>Four levels of help.</strong><span>One connected Trios request.</span></span></div></div></div></section><div className="container moving-jump-links"><a href="#moving-tiers">Tiers <ArrowRight size={18} /></a><a href="#moving-tier-finder">Tier finder <ArrowRight size={18} /></a><a href="#moving-inclusions">Compare scope <ArrowRight size={18} /></a><a href="#moving-preparation">Prepare <ArrowRight size={18} /></a><a href="#moving-questions">Questions <ArrowRight size={18} /></a></div>
    {selectedTier && <section className="container moving-section moving-selected-tier"><div><div className="eyebrow">YOUR TIER, EXPLAINED</div><h2>{selectedTier.eyebrow}</h2><p>{selectedTier.summary}</p><div className="moving-scope-note"><strong>What needs agreement</strong><p>{selectedTier.boundary}</p></div></div><div><h3>Build the scope around these tasks</h3><ul className="moving-checks">{selectedTier.includes.map(item => <li key={item}><CheckCircle2 size={22} /><span>{item}</span></li>)}</ul><a className="button" href={quoteUrl(selectedTier.id)}>Request {selectedTier.name} <ArrowRight size={21} /></a></div></section>}
    <section className="container moving-section" id="moving-tiers"><div className="moving-section-heading"><div><div className="eyebrow">AS MUCH HELP AS YOU NEED</div><h2>Four tiers.<br /><span>Your kind of move.</span></h2></div><p>Start with the level of support that feels right. Every tier is assessed and quoted for your inventory, access and agreed tasks.</p></div><div className="moving-tier-grid">{MOVING_TIERS.map((tier, index) => { const Icon = tierIcons[tier.id as TierId]; return <article className={'moving-tier-card' + (tier.id === 'pack' ? ' moving-tier-highlight' : '')} key={tier.id}><div className="moving-tier-top"><Icon size={30} /><span>0{index + 1}</span></div><div className="eyebrow">{tier.eyebrow}</div><h3>{tier.name}</h3><p>{tier.summary}</p><ul className="moving-checks">{tier.includes.map(item => <li key={item}><Check size={20} /><span>{item}</span></li>)}</ul><details><summary>Scope to review <Plus size={20} /></summary><p>{tier.boundary}</p></details><div className="moving-tier-price"><strong>Personalized quote</strong><span>Scope & arrangements confirmed first</span></div><a className={'button full' + (tier.id === 'pack' ? ' lime' : ' outline')} href={quoteUrl(tier.id)}>Choose this tier <ArrowUpRight size={20} /></a><a className="moving-tier-detail" href={'/moving/' + tier.id}>Explore {tier.name} <ArrowRight size={18} /></a></article>; })}</div></section>
    <section className="moving-soft-section"><div className="container moving-section"><TierFinder /></div></section>
    <section className="container moving-section"><div className="moving-section-heading"><div><div className="eyebrow">EVERY MOVE HAS ITS OWN DETAILS</div><h2>From a single room<br /><span>to your next home.</span></h2></div><p>Tell us what is changing. We’ll review the belongings, route and access before confirming the right resources.</p></div><div className="moving-situation-tabs" aria-label="Explore move types">{situations.map(item => <button type="button" key={item.id} aria-pressed={situation === item.id} onClick={() => setSituation(item.id)}>{item.name}</button>)}</div><div className="moving-situation-panel" aria-live="polite"><div><MapPin size={31} /><h3>{currentSituation.name}</h3><p>{currentSituation.summary}</p></div><div><strong>Useful details for your request</strong><p>{currentSituation.detail}</p><a className="text-link" href={'/book?service=moving&moveType=' + encodeURIComponent(moveTypeNames[situation])}>Start with my inventory <ArrowRight size={21} /></a></div></div></section>
    <section className="container moving-section moving-no-top" id="moving-inclusions"><div className="moving-section-heading"><div><div className="eyebrow">CLEAR BEFORE YOU COMMIT</div><h2>See how the<br /><span>support adds up.</span></h2></div><p>These are proposed tier scopes, not confirmed inclusions. Your accepted written quote takes precedence.</p></div><div className="moving-comparison-scroll" tabIndex={0} role="region" aria-label="Moving tier comparison; scroll horizontally on smaller screens"><table><caption>Moving tier scope comparison</caption><thead><tr><th scope="col">Planning & tasks</th>{MOVING_TIERS.map(tier => <th key={tier.id} scope="col">{tier.name}</th>)}</tr></thead><tbody>{comparison.map(row => <tr key={row[0]}>{row.map((cell, index) => index === 0 ? <th scope="row" key={cell}>{cell}</th> : <td key={index}>{cell}</td>)}</tr>)}</tbody></table></div><p className="moving-comparison-hint">On smaller screens, swipe the table to compare every tier.</p></section>
    <section className="moving-soft-section"><div className="container moving-section"><div className="moving-section-heading"><div><div className="eyebrow">SHAPE THE DETAILS</div><h2>A few useful extras.<br /><span>A more complete plan.</span></h2></div><p>Add options in your moving request. Trios reviews what is appropriate and lists accepted additions in your quote.</p></div><div className="moving-addon-grid">{MOVING_ADDONS.map(addon => <article key={addon.id}><span><Plus size={22} /></span><h3>{addon.name}</h3><p>{addon.description}</p></article>)}</div><div className="moving-care-bundle"><House size={34} /><div><h3>Make the handover feel complete.</h3><p>Request moving alongside home cleaning, lawn care or seasonal property work. Keep the quote and schedule for every agreed service together.</p></div><a className="button" href="/book?services=moving,cleaning&tier=complete">Moving + cleaning request <ArrowRight size={20} /></a></div></div></section>
    <section className="container moving-section"><div className="moving-section-heading"><div><div className="eyebrow">A QUOTE THAT STARTS WITH THE FACTS</div><h2>Your belongings.<br /><span>Your addresses. Your scope.</span></h2></div><p>No generic moving total. The details you provide help build a clear, itemized assessment.</p></div><div className="moving-factor-grid">{[[Box, 'What is moving', 'Inventory, quantities, large dimensions, fragile pieces and packing needs.'], [MapPin, 'How we get there', 'Both addresses, stairs, elevators, loading space, carry distance and extra stops.'], [ClipboardList, 'What you need done', 'Labour, transport, packing materials, assembly and agreed destination placement.'], [ClipboardCheck, 'When it can happen', 'Your preferred date, flexibility, building restrictions and realistic resource needs.']].map(([Icon, title, text]) => { const FactorIcon = Icon as typeof Box; return <article key={String(title)}><FactorIcon size={28} /><h3>{String(title)}</h3><p>{String(text)}</p></article>; })}</div><ol className="moving-process"><li><span>01</span><div><h3>Build your move brief</h3><p>Choose a tier, list your inventory and tell us about both addresses.</p></div></li><li><span>02</span><div><h3>Agree the plan</h3><p>Review the assessed scope, transport arrangements, price and service terms.</p></div></li><li><span>03</span><div><h3>Keep the move together</h3><p>Follow accepted work, visit details, completion records and invoices in your account.</p></div></li></ol></section>
    <section className="moving-soft-section"><div className="container moving-section"><MovingChecklist /></div></section>
    <section className="container moving-section" id="moving-questions"><div className="moving-section-heading"><div><div className="eyebrow">BEFORE THE FIRST BOX</div><h2>Moving questions,<br /><span>answered clearly.</span></h2></div><label className="moving-faq-search">Find an answer<input type="search" value={faqQuery} onChange={e => setFaqQuery(e.target.value)} placeholder="Try packing, truck or date" /></label></div><div className="public-faq-list">{visibleFaqs.map(([question, answer]) => <details key={question}><summary><span>{question}</span><Plus size={22} /></summary><p>{answer}</p></details>)}</div>{!visibleFaqs.length && <div className="moving-no-answers"><p>No matching questions. Try another word or speak with Trios.</p><button type="button" className="button outline" onClick={() => setFaqQuery('')}>Show all answers</button></div>}</section>
    <section className="container moving-final-cta"><div><div className="eyebrow">LET’S MAKE ROOM FOR WHAT’S NEXT</div><h2>Your next chapter<br />starts with a plan.</h2><p>Tell us where you’re going and what you need help with.</p></div><div><a className="button lime" href={selectedTier ? quoteUrl(selectedTier.id) : '/book?service=moving'}>Build my moving request <ArrowUpRight size={22} /></a><a href={'tel:' + CONTACT.tel}><Phone size={20} />Talk it through: {CONTACT.phone}</a></div></section>
  </div>;
}
