'use client';
import { useEffect, useRef, useState } from 'react';
import { Plus, ArrowRight, CalendarDays, Users, Check, Download, MapPin, Search, Settings2, Wallet } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Pick, Notice, saveData, ErrorNotice } from './shared';
import { SERVICES, AREAS, money, niceDate } from '@/lib/catalog';
import { localToday } from '@/lib/validation';
import { toast } from 'sonner';
export function IntakeFields({form,edit}:{form:any;edit:(k:string,v:any)=>void}){return <>
 <div className="wide"><Notice>Record a customer enquiry received by phone, email or in person. The customer gets a separate record and can access it by signing in with the same email.</Notice></div>
 <label>Customer’s full name<input required minLength={2} maxLength={100} autoComplete="name" value={form.name} onChange={e=>edit('name',e.target.value)}/></label>
 <label>Customer email<input required type="email" autoComplete="email" value={form.email} onChange={e=>edit('email',e.target.value)}/></label>
 <label>Phone number<input required type="tel" minLength={7} autoComplete="tel" value={form.phone} onChange={e=>edit('phone',e.target.value)}/></label>
 <div className="field"><label>Enquiry received through</label><Pick label="Enquiry source" value={form.source} options={['Phone','Email','In person']} onChange={v=>edit('source',v)}/></div>
 <label className="wide">Property address<input required minLength={5} value={form.address} onChange={e=>edit('address',e.target.value)}/></label>
 <div className="field"><label>Community</label><Pick label="Customer community" value={form.area} onChange={v=>edit('area',v)} options={AREAS}/></div>
 <label>Postal code<input required maxLength={7} value={form.postalCode} onChange={e=>edit('postalCode',e.target.value.toUpperCase())} placeholder="A1A 1A1"/></label>
 <fieldset className="wide"><legend className="section-title">Requested services</legend><div className="choice-grid">{SERVICES.map(s=><label className="checkbox-row intake-service" key={s.id}><Checkbox checked={form.services.includes(s.id)} onCheckedChange={v=>edit('services',v?[...form.services,s.id]:form.services.filter((id:string)=>id!==s.id))}/>{s.name}</label>)}</div></fieldset>
 <div className="field wide"><label>Frequency</label><Pick value={form.frequency} onChange={v=>edit('frequency',v)} options={['One-time','Weekly','Every two weeks','Seasonal','Year-round']}/></div>
 <label className="wide">Access details and customer requirements<textarea rows={4} maxLength={2000} value={form.notes} onChange={e=>edit('notes',e.target.value)} placeholder="Gate access, driveway dimensions, preferred service timing and anything the crew should know."/></label>
 <label className="wide checkbox-row"><Checkbox checked={form.consent} onCheckedChange={v=>edit('consent',v===true)}/>The customer asked us to record this enquiry and use these details to arrange service.</label>
 </>}
export function ApprovalFields({form,edit}:{form:any;edit:(k:string,v:any)=>void}){return <>
 <div className="wide summary-mini"><strong>Quote total: {money(form.request.quote_total/100)}</strong><p style={{whiteSpace:'pre-wrap',marginTop:12}}>{form.request.quote_terms}</p></div>
 <label>Customer who approved<input required minLength={2} value={form.signer} onChange={e=>edit('signer',e.target.value)}/></label>
 <div className="field"><label>Approval received through</label><Pick value={form.method} onChange={v=>edit('method',v)} options={['Phone','Email','Signed document','In person']}/></div>
 <label className="wide">Approval evidence<textarea required minLength={15} maxLength={2000} rows={4} value={form.evidence} onChange={e=>edit('evidence',e.target.value)} placeholder="Record when approval was received, what was agreed, and the email or signed document reference."/></label>
 <label className="checkbox-row wide"><Checkbox checked={form.confirmed} onCheckedChange={v=>edit('confirmed',v===true)}/>I have received the customer’s approval for this exact price and scope.</label>
 </>}
export function BusinessSettings({initial,refresh}:{initial:any;refresh:()=>void}){const [form,setForm]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false);const settingsSnapshot=JSON.stringify(initial),lastSnapshot=useRef(settingsSnapshot);useEffect(()=>{if(!dirty&&lastSnapshot.current!==settingsSnapshot){setForm(initial);lastSnapshot.current=settingsSnapshot}},[initial,dirty,settingsSnapshot]);function edit(k:string,v:any){setDirty(true);setForm({...form,[k]:v})}return <form className="white-card settings-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await saveData({...form,action:'settings'});toast.success('Operating settings saved');setDirty(false);refresh()}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setBusy(false)}}}>
 <h3>Make the workspace fit your business</h3><p>These settings apply to new quotes, invoice due dates and dispatch assignments.</p>
 {error&&<ErrorNotice message={error}/>}<div className="form-grid">
 <label>Maximum visits per crew member per day<input type="number" required min={1} max={100} value={form.dailyCapacity} onChange={e=>edit('dailyCapacity',Number(e.target.value))}/></label>
 <label>Default invoice payment term (days)<input type="number" required min={0} max={90} value={form.invoiceDays} onChange={e=>edit('invoiceDays',Number(e.target.value))}/></label>
 <label className="wide">Default quote scope and terms<textarea rows={7} maxLength={4000} value={form.quoteTerms} onChange={e=>edit('quoteTerms',e.target.value)} placeholder="Add your usual service scope, snowfall trigger, arrival windows, exclusions, taxes and cancellation arrangements. Review for each customer."/></label>
 <label className="wide">Payment instructions shown on invoices<textarea rows={4} maxLength={2000} value={form.paymentInstructions} onChange={e=>edit('paymentInstructions',e.target.value)}/></label></div>
 <div className="button-row"><button disabled={busy} className="button"><Check size={20}/>{busy?'Saving…':'Save operating settings'}</button>{dirty&&<button type="button" className="button outline" disabled={busy} onClick={()=>{setForm(initial);setDirty(false)}}>Discard unsaved changes</button>}<span className="small-text" role="status">{dirty?'You have unsaved settings.':'Using saved operating settings.'}</span></div></form>}
export function CustomerDirectory({data,search,onRequest,onCreate}:{data:any;search:string;onRequest:(id:string)=>void;onCreate:()=>void}){const grouped=new Map<string,any>();for(const r of data.requests){const key=r.email.toLowerCase();if(!grouped.has(key))grouped.set(key,{name:r.customer_name,email:r.email,phone:r.phone,requests:[]});grouped.get(key).requests.push(r)}const customers=[...grouped.values()].filter(c=>`${c.name} ${c.email} ${c.phone} ${c.requests.map((r:any)=>r.address).join(' ')}`.toLowerCase().includes(search.toLowerCase()));return <>
 <div className="section-head"><div><h3>People behind the properties</h3><p>{customers.length} customer{customers.length===1?'':'s'} · contact details, properties and service history</p></div><button className="button" onClick={onCreate}><Plus size={20}/>Add customer request</button></div>
 <div className="customer-grid">{customers.map(c=>{const ids=c.requests.map((r:any)=>r.id);const invoices=data.invoices.filter((i:any)=>ids.includes(i.request_id));const balance=invoices.reduce((a:number,i:any)=>a+i.amount_cents+i.tax_cents-(i.paid_cents||0),0);return <article className="white-card customer-card" key={c.email}><div className="customer-heading"><span className="customer-avatar">{c.name.split(' ').map((n:string)=>n[0]).slice(0,2).join('')}</span><div><h3>{c.name}</h3><a href={'mailto:'+c.email}>{c.email}</a></div></div><a className="text-link" href={'tel:'+c.phone}>{c.phone}</a><div className="summary-line"><span>Service requests</span><strong>{c.requests.length}</strong></div><div className="summary-line"><span>Outstanding balance</span><strong>{money(balance/100)}</strong></div>{c.requests.map((r:any)=><button key={r.id} className="customer-property" onClick={()=>onRequest(r.id)}><span><strong>{r.address}</strong><span>{r.area} · {r.status}</span></span><ArrowRight size={21}/></button>)}</article>})}</div>
 {!customers.length&&<div className="white-card empty-state"><Users size={36}/><h3>{search?'No customers match this search.':'Start with your first customer.'}</h3><p>{search?'Try a name, email, phone number or property address.':'Add a phone or email enquiry, then prepare their quote.'}</p><button className="button" onClick={onCreate}><Plus size={20}/>Add customer request</button></div>}
 <a className="button outline" style={{marginTop:24}} href="/api/export?type=customers"><Download size={20}/>Export customer list</a>
 </>}
export function DispatchTools({data,jobs,onSaved}:{data:any;jobs:any[];onSaved:()=>void}) {
 const [selected,setSelected]=useState<string[]>([]),[crewId,setCrewId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[commandId,setCommandId]=useState(()=>crypto.randomUUID());
 const eligible=jobs.filter(j=>['scheduled','in_progress'].includes(j.status)),chosen=eligible.filter(j=>selected.includes(j.id)),capacity=data.settings?.dailyCapacity||12;
 const activeCrew=data.crew.filter((c:any)=>c.active),target=activeCrew.find((c:any)=>c.id===crewId);
 const days=[...new Set(chosen.map(j=>j.scheduled_date))].sort();
 const projected=days.map(day=>({day,count:data.jobs.filter((j:any)=>j.scheduled_date===day&&['scheduled','in_progress'].includes(j.status)&&(j.crew_id===crewId||chosen.some(v=>v.id===j.id))).length}));
 const exceeds=projected.some(d=>d.count>capacity);
 function changeSelected(ids:string[]){setSelected([...new Set(ids)].slice(0,100));setError('');setCommandId(crypto.randomUUID())}
 useEffect(()=>{const visible=new Set(eligible.map(j=>j.id));setSelected(current=>current.filter(id=>visible.has(id)))},[jobs]);
 return <div className="dispatch-panel ops-bulk-panel"><div className="section-head"><div><div className="eyebrow">BULK ASSIGNMENT</div><h3>Assign the selected visits.</h3><p>Choose up to 100 open visits. The daily crew limit is {capacity}; the server checks every assignment before saving.</p></div></div>
 {error&&<ErrorNotice message={error}/>}
 {!activeCrew.length?<Notice>Add an active crew member in Team before assigning visits.</Notice>:<>
 <div className="dispatch-select"><label className="checkbox-row"><Checkbox disabled={busy} checked={eligible.length>0&&chosen.length===Math.min(eligible.length,100)} onCheckedChange={v=>changeSelected(v===true?eligible.slice(0,100).map(j=>j.id):[])}/>Select {eligible.length>100?'the first 100':`all ${eligible.length}`} open visits in this view</label></div>
 <div className="dispatch-choices">{eligible.map(j=><label className="dispatch-choice" key={j.id}><Checkbox checked={selected.includes(j.id)} disabled={busy||(!selected.includes(j.id)&&chosen.length>=100)} onCheckedChange={v=>changeSelected(v===true?[...selected,j.id]:selected.filter(id=>id!==j.id))}/><span><strong>{j.address}</strong><span>{niceDate(j.scheduled_date)} · {j.time_window} · {j.crew_name||'Unassigned'}</span></span></label>)}</div>
 {!eligible.length&&<p className="ops-soft-empty">No open visits in the current view. Change the date or filters to find work to assign.</p>}
 <div className="dispatch-actions"><strong>{chosen.length} selected</strong><Pick label="Assign selected visits to crew" value={crewId} disabled={busy} onChange={v=>{setCrewId(v);setError('');setCommandId(crypto.randomUUID())}} options={activeCrew.map((c:any)=>({value:c.id,label:c.name}))}/><button type="button" className="button" disabled={busy||!target||!chosen.length||exceeds} onClick={async()=>{if(busy)return;setBusy(true);setError('');try{await saveData({action:'dispatch',commandId,crewId,jobs:chosen.map(j=>({id:j.id,version:j.version}))});toast.success('Crew assignments saved');changeSelected([]);onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to dispatch')}finally{setBusy(false)}}}>{busy?'Assigning…':'Assign selected visits'}<ArrowRight size={20}/></button></div>
 {target&&chosen.length>0&&<div className={'ops-capacity-preview'+(exceeds?' at-limit':'')} role="status"><strong>{target.name} after this assignment</strong>{projected.map(d=><span key={d.day}>{niceDate(d.day)}: {d.count} / {capacity} open visits{d.count>capacity?' · exceeds capacity':''}</span>)}{exceeds&&<p>Reduce the selection or choose another crew member. Capacity can be adjusted in Settings when appropriate.</p>}</div>}
 <p className="small-text muted" style={{marginTop:16}}>Capacity includes that crew member’s other open visits, even when they are hidden by your filters.</p></>}
 </div>
}
export function ActionBoard({data,onTab,onCreate}:{data:any;onTab:(tab:string,status?:string)=>void;onCreate:()=>void}){const unquoted=data.requests.filter((r:any)=>r.status==='requested').length,unscheduled=data.requests.filter((r:any)=>r.status==='accepted'&&!data.jobs.some((j:any)=>j.request_id===r.id&&j.status!=='cancelled')).length;const due=data.invoices.filter((i:any)=>i.status!=='paid'&&i.due_date<localToday());return <div className="action-board"><div><div className="eyebrow">YOUR NEXT MOVES</div><h3>Keep the day moving.</h3><p>Every action connects to a saved customer record.</p></div><div className="action-grid">{[{n:unquoted,label:'Requests to quote',tab:'Requests',status:'requested',Icon:ArrowRight},{n:unscheduled,label:'Approved, awaiting first visit',tab:'Requests',status:'accepted',Icon:CalendarDays},{n:due.length,label:'Overdue invoices',tab:'Billing',Icon:Wallet}].map(a=><button className="action-tile" key={a.label} onClick={()=>onTab(a.tab,a.status)}><a.Icon size={25}/><strong>{a.n}</strong><span>{a.label}</span><ArrowRight size={20}/></button>)}</div><button className="button lime" onClick={onCreate}><Plus size={20}/>Record a new customer enquiry</button></div>}
