'use client';

import { useEffect, useRef, useState } from 'react';
import { Plus, ArrowUpRight, CalendarDays, MapPin, Clock, Check, House, Mail, Download, RefreshCw, ArrowRight, Search, FileCheck2, CreditCard, MessageCircle, ClipboardList, Copy, CheckCircle2, ChevronRight } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { toast } from 'sonner';
import { Intro } from './site-app';
import { useData, saveData, Loading, ErrorNotice, Empty, SignIn, Pick, Notice } from './shared';
import { ServiceChanges } from './service-changes';
import { MovingWorkspace } from './moving-workspace';
import { MovingBrief } from './moving-intake';
import { SERVICES, AREAS, CONTACT, money, niceDate } from '@/lib/catalog';
import { CustomerContact, CustomerPrivacyNote, useCustomerReadiness, parseList, parseDetails, customerToday, invoiceBalance, reference } from './customer-tools';

export const serviceName = (id: string) => SERVICES.find(service => service.id === id)?.name || id;
export function Status({ value }: { value: string }) { return <span className={'pill ' + value}>{String(value).replaceAll('_', ' ')}</span>; }
const blankProperty = { label: 'Home', address: '', area: 'St. John’s', postalCode: '', details: '' };

export function Portal() {
  const { data, error, loading, refresh } = useData();
  const { readiness, retry } = useCustomerReadiness();
  const [tab, setTab] = useState('overview');
  const [property, setProperty] = useState<any>(null), [quote, setQuote] = useState<any>(null), [cancel, setCancel] = useState<any>(null), [invoice, setInvoice] = useState<any>(null);
  const [saving, setSaving] = useState(false), [subject, setSubject] = useState(''), [body, setBody] = useState('');
  const [search, setSearch] = useState(''), [requestFilter, setRequestFilter] = useState('all'), [visitFilter, setVisitFilter] = useState('upcoming'), [billingFilter, setBillingFilter] = useState('all');
  const [selectedRecord, setSelectedRecord] = useState('all'), [messageFilter, setMessageFilter] = useState('all');
  const messageHeading = useRef<HTMLHeadingElement>(null);
  const mutationSession = useRef(0), mounted = useRef(true);
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('tab'); if (value && ['overview', 'requests', 'visits', 'properties', 'billing', 'messages', 'changes', 'moving'].includes(value)) setTab(value); }, []);
  useEffect(() => { setSearch(''); }, [tab]);
  useEffect(() => {
    mounted.current = true;
    const reset = () => { ++mutationSession.current; setSaving(false); setProperty(null); setQuote(null); setCancel(null); setInvoice(null); setSubject(''); setBody(''); setSearch(''); };
    window.addEventListener('trios:signout', reset); return () => { mounted.current = false; ++mutationSession.current; window.removeEventListener('trios:signout', reset); };
  }, []);
  async function mutate(payload: any, success = 'Changes saved') {
    if (saving) return false;
    const currentSession = mutationSession.current;
    const isCurrent = () => mounted.current && mutationSession.current === currentSession;
    setSaving(true);
    try { await saveData(payload); if (!isCurrent()) return false; toast.success(success); await refresh(); return isCurrent(); }
    catch (exception) { if (isCurrent()) toast.error(exception instanceof Error ? exception.message : 'Could not save. Please try again.'); return false; }
    finally { if (isCurrent()) setSaving(false); }
  }
  function compose(nextSubject: string, nextBody = '') { setSubject(nextSubject); setBody(nextBody); setTab('messages'); window.setTimeout(() => messageHeading.current?.focus(), 50); }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); toast.success('Reference copied'); } catch { toast.error('Copy is unavailable. Select the reference to copy it.'); } }

  if (loading && !data) return <div className="container section"><Loading/></div>;
  if (readiness && !readiness.accountsAvailable && !data?.user) return <><Intro eyebrow="YOUR PROPERTY ACCOUNT" title="Your property, beautifully organized.">Quotes, service visits, invoices and property notes in one private account.</Intro><div className="container page-body customer-upgrade"><CustomerContact retry={retry}/><div className="customer-preview-grid">{[[ClipboardList, 'Your requests', 'Review your scope and accept your final quote.'], [CalendarDays, 'Your service calendar', 'Confirmed visits, arrival windows and completion records.'], [House, 'Your property passport', 'Saved addresses, access notes and service history.']].map(([Icon, title, description]: any) => <div className="white-card" key={title}><Icon size={28}/><h3>{title}</h3><p>{description}</p></div>)}</div></div></>;
  if (error && !data) return <div className="container section"><ErrorNotice message={error} retry={refresh}/><div className="spacer"/><CustomerContact compact unavailable={readiness?.bookingAvailable !== true}/></div>;
  if (!data?.user) return <div className="container section"><SignIn/></div>;

  const { requests = [], properties = [], jobs = [], invoices = [], messages = [], events = [] } = data;
  const today = customerToday();
  const openInvoices = invoices.filter((item: any) => invoiceBalance(item) > 0);
  const balance = openInvoices.reduce((total: number, item: any) => total + invoiceBalance(item), 0);
  const overdue = openInvoices.filter((item: any) => item.due_date && item.due_date < today);
  const upcoming = jobs.filter((job: any) => ['scheduled', 'in_progress'].includes(job.status)).sort((a: any, b: any) => (a.scheduled_date || '').localeCompare(b.scheduled_date || ''));
  const completed = jobs.filter((job: any) => job.status === 'completed');
  const pendingQuotes = requests.filter((request: any) => request.status === 'quoted');
  const replied = messages.filter((message: any) => message.reply);
  const query = search.trim().toLowerCase();
  const matches = (...values: unknown[]) => !query || values.some(value => String(value || '').toLowerCase().includes(query));
  const filteredRequests = requests.filter((request: any) => (requestFilter === 'all' || request.status === requestFilter) && matches(request.address, reference(request.id), ...parseList(request.services).map(serviceName)));
  const filteredVisits = jobs.filter((job: any) => (visitFilter === 'all' || (visitFilter === 'upcoming' ? ['scheduled', 'in_progress'].includes(job.status) : job.status === visitFilter)) && matches(job.address, serviceName(job.service), reference(job.request_id))).sort((a: any, b: any) => visitFilter === 'upcoming' ? String(a.scheduled_date || '').localeCompare(String(b.scheduled_date || '')) : String(b.scheduled_date || '').localeCompare(String(a.scheduled_date || '')));
  const filteredInvoices = invoices.filter((item: any) => (billingFilter === 'all' || (billingFilter === 'open' ? invoiceBalance(item) > 0 : billingFilter === 'overdue' ? invoiceBalance(item) > 0 && item.due_date && item.due_date < today : invoiceBalance(item) === 0)) && matches(item.description, item.address, reference(item.id)));
  const filteredEvents = events.filter((event: any) => selectedRecord === 'all' || event.request_id === selectedRecord);
  const filteredMessages = messages.filter((message: any) => (messageFilter === 'all' || (messageFilter === 'replied' ? !!message.reply : !message.reply)) && matches(message.subject, message.body, message.reply));
  const searchBox = (placeholder: string) => <label className="customer-search"><Search size={19}/><span className="sr-only">{placeholder}</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder={placeholder}/></label>;

  return <><Intro eyebrow="YOUR PROPERTY ACCOUNT" title={`Hello, ${(data.user.name || 'there').split(' ')[0]}.`}>Your property care and moving plans. Every request, visit and detail, together.</Intro>
    <div className="container page-body customer-upgrade">
      <div className="customer-account-bar"><div><span className="customer-kicker">PRIVATE CUSTOMER ACCOUNT</span><p className="account-email">{data.user.email}</p></div><div className="button-row"><button className="button small outline" disabled={loading} onClick={refresh} aria-label="Refresh account records"><RefreshCw size={17} className={loading ? 'spin' : ''}/><span>Refresh</span></button><a className="button small" href="/book"><Plus size={17}/>Request care</a><a className="text-link" target="_top" href="/sign-out?return_to=%2Fportal" onClick={() => window.dispatchEvent(new Event('trios:signout'))}>Sign out</a></div></div>
      {error && <div className="customer-inline-gap"><ErrorNotice message={error} retry={refresh}/></div>}
      <Tabs value={tab} onValueChange={setTab}><TabsList className="service-tabs customer-tabs">{[['overview', 'Overview'], ['requests', 'Requests & quotes'], ['visits', 'Service visits'], ['moving', 'My moves'], ['properties', 'Properties'], ['billing', 'Invoices'], ['changes', 'Service requests'], ['messages', 'Messages']].map(([value, label]) => <TabsTrigger value={value} key={value}>{label}{value === 'requests' && pendingQuotes.length > 0 && <span className="customer-tab-count">{pendingQuotes.length}</span>}</TabsTrigger>)}</TabsList>
        <TabsContent value="overview">
          <div className="customer-summary-band"><div><span className="customer-kicker">YOUR CARE AT A GLANCE</span><h2>{upcoming.length ? 'Your next chapter is already planned.' : 'Make more room for your day.'}</h2><p>{upcoming.length ? `${upcoming.length} open service visit${upcoming.length === 1 ? '' : 's'} · ${properties.length} saved propert${properties.length === 1 ? 'y' : 'ies'}` : 'Start a request and we’ll help build a care plan around your property.'}</p></div><a href="/book?plan=annual" className="button lime">Build a seasonal plan <ArrowUpRight size={19}/></a></div>
          <div className="moving-customer-entry"><div><h3>{requests.some((request:any)=>parseList(request.services).includes('moving'))?'Your moving plans, connected.':'A new home. The same care team.'}</h3><p>{requests.some((request:any)=>parseList(request.services).includes('moving'))?'Review your moving request, inventory and saved move-day updates.':'Choose from four moving tiers and build an inventory and access plan.'}</p></div>{requests.some((request:any)=>parseList(request.services).includes('moving'))?<button type="button" className="button outline" onClick={()=>setTab('moving')}>Open my moves <ArrowRight size={18}/></button>:<a className="button outline" href="/moving">Explore moving <ArrowRight size={18}/></a>}</div>
          <div className="customer-metrics">{[[FileCheck2, 'Quotes to review', pendingQuotes.length, 'requests'], [CalendarDays, 'Upcoming visits', upcoming.length, 'visits'], [CheckCircle2, 'Completed visits', completed.length, 'visits'], [CreditCard, 'Outstanding balance', money(balance / 100), 'billing']].map(([Icon, label, value, target]: any) => <button type="button" className="customer-metric" key={label} onClick={() => { setTab(target); if (label === 'Completed visits') setVisitFilter('completed'); else if (target === 'visits') setVisitFilter('upcoming'); }}><Icon size={22}/><span>{label}</span><strong>{value}</strong><ArrowUpRight size={17} className="customer-metric-arrow"/></button>)}</div>
          <div className="customer-overview-grid"><section><div className="section-head"><h3>Your next visit</h3><button className="text-link" onClick={() => { setTab('visits'); setVisitFilter('upcoming'); }}>View visits <ArrowRight size={17}/></button></div>{upcoming.length ? <VisitCard job={upcoming[0]} onMessage={compose}/> : <Empty title="A little care goes a long way." action={<a className="button" href="/book">Request property care <ArrowUpRight size={17}/></a>}>Your confirmed visits will appear here after you accept a quote and scheduling is agreed.</Empty>}
            <div className="white-card customer-prep"><h3>Ready for your next visit?</h3><ul><li>Keep the agreed work area clear of vehicles and loose items.</li><li>Check gate access and keep pets safely indoors.</li><li>Add changing access needs to a message before the visit.</li></ul><button className="text-link" onClick={() => compose('Access notes for my next visit')}>Send an access update <ArrowRight size={17}/></button></div></section>
            <section><div className="section-head"><h3>Your next steps</h3><span className="customer-kicker">PERSONAL TO YOUR ACCOUNT</span></div><div className="white-card customer-actions">{upcoming.length > 0 && <button className="customer-action" onClick={() => setTab('changes')}><CalendarDays size={25}/><span><strong>Need a service change?</strong><small>Request a different date or report a service issue</small></span><ChevronRight size={20}/></button>}{pendingQuotes.length > 0 && <button className="customer-action" onClick={() => setQuote(pendingQuotes[0])}><FileCheck2 size={25}/><span><strong>Review your quote</strong><small>{pendingQuotes.length} quote{pendingQuotes.length > 1 ? 's' : ''} waiting for your decision</small></span><ChevronRight size={20}/></button>}{openInvoices.length > 0 && <button className="customer-action" onClick={() => { setTab('billing'); setBillingFilter('open'); }}><CreditCard size={25}/><span><strong>{overdue.length ? 'Review overdue invoices' : 'View your payment details'}</strong><small>{money(balance / 100)} outstanding · verified payments only</small></span><ChevronRight size={20}/></button>}{!properties.length && <button className="customer-action" onClick={() => setProperty({ ...blankProperty })}><House size={25}/><span><strong>Add your property passport</strong><small>Save your address and important access notes</small></span><ChevronRight size={20}/></button>}{replied.length > 0 && <button className="customer-action" onClick={() => { setTab('messages'); setMessageFilter('replied'); }}><MessageCircle size={25}/><span><strong>Read replies from Trios</strong><small>{replied.length} conversation{replied.length > 1 ? 's' : ''} with a team response</small></span><ChevronRight size={20}/></button>}<button className="customer-action" onClick={() => compose('A question about my property care')}><Mail size={25}/><span><strong>Talk to your care team</strong><small>Questions, access changes or service concerns</small></span><ChevronRight size={20}/></button></div></section></div>
          <div className="section-head"><h3>Your service timeline</h3><div className="customer-select"><Pick label="Filter updates by request" value={selectedRecord} onChange={setSelectedRecord} options={[{ value: 'all', label: 'All requests' }, ...requests.map((request: any) => ({ value: request.id, label: reference(request.id) + ' · ' + request.address }))]}/></div></div>
          {filteredEvents.length ? <ol className="customer-timeline white-card">{filteredEvents.slice(0, 20).map((event: any) => <li key={event.id}><span className="customer-timeline-dot"/><div><strong>{event.body}</strong><span>{reference(event.request_id)} · {niceDate(event.created_at)}</span></div></li>)}</ol> : <Notice>Your quote, scheduling and completion updates appear here as your care progresses.</Notice>}
        </TabsContent>

        <TabsContent value="requests"><div className="customer-filter-row">{searchBox('Search requests, services or address')}<Pick label="Request status" value={requestFilter} onChange={setRequestFilter} options={[{ value: 'all', label: 'All requests' }, { value: 'requested', label: 'Awaiting quote' }, { value: 'quoted', label: 'Ready to review' }, { value: 'accepted', label: 'Accepted' }, { value: 'cancelled', label: 'Cancelled' }]}/></div>
          {!filteredRequests.length ? <Empty title={requests.length ? 'No requests match these filters.' : 'What can we take off your list?'} action={<a className="button" href="/book">Build my quote <ArrowUpRight size={17}/></a>}>Request a single service or put a full seasonal care plan together.</Empty> : filteredRequests.map((request: any) => <article className="list-card customer-request-card" key={request.id}><div className="list-card-head"><div><button className="customer-reference" onClick={() => copy(reference(request.id))}>{reference(request.id)}<Copy size={15}/></button><h3>{parseList(request.services).map(serviceName).join(' + ')}</h3></div><Status value={request.status}/></div><div className="list-meta"><span><MapPin size={17}/>{request.address}</span><span><CalendarDays size={17}/>{niceDate(request.created_at)}</span><span>{request.frequency}</span></div><RequestProgress request={request} jobs={jobs.filter((job: any) => job.request_id === request.id)}/><div className="button-row">{request.status === 'quoted' && <button className="button small" onClick={() => setQuote(request)}>Review quote · {money(request.quote_total / 100)}<ArrowRight size={17}/></button>}{request.status === 'accepted' && <button className="button small outline" onClick={() => setQuote(request)}>View accepted quote</button>}<button className="button small outline" onClick={() => compose('Question about ' + reference(request.id), `Property: ${request.address}\nRequest: ${reference(request.id)}\n\n`)}>Ask a question</button>{['requested', 'quoted'].includes(request.status) && <button className="text-link customer-muted-action" onClick={() => setCancel(request)}>Cancel request</button>}</div><details className="customer-details"><summary>View submitted property details</summary><RequestDetails request={request}/></details></article>)}
        </TabsContent>

        <TabsContent value="visits"><div className="section-head"><div><h3>Your service calendar</h3><p className="small-text">Dates and arrival windows use St. John’s time.</p></div>{jobs.length > 0 && <a className="button outline" href="/api/calendar"><Download size={18}/>Add to calendar</a>}</div><div className="customer-filter-row">{searchBox('Search visits by service or address')}<Pick label="Visit status" value={visitFilter} onChange={setVisitFilter} options={[{ value: 'upcoming', label: 'Upcoming & in progress' }, { value: 'completed', label: 'Completed visits' }, { value: 'cancelled', label: 'Cancelled visits' }, { value: 'all', label: 'All visits' }]}/></div>{!filteredVisits.length ? <Empty title="No visits in this view." action={<button className="button outline" onClick={() => setTab('requests')}>View my requests</button>}>Confirmed visits appear here with their service window, team and completion notes.</Empty> : filteredVisits.map((job: any) => <VisitCard key={job.id} job={job} onMessage={compose}/>)}{jobs.length > 0 && <p className="small-text muted">Calendar downloads create all-day events. Each entry includes the agreed time window in its notes; download again after a schedule change.</p>}</TabsContent>

        <TabsContent value="moving"><MovingWorkspace key={data.user.id+':customer'} data={data} mode="customer" refresh={refresh} onNavigate={setTab}/></TabsContent>
        <TabsContent value="properties"><div className="section-head"><div><span className="customer-kicker">YOUR PROPERTY PASSPORTS</span><h3>Good care starts with the details.</h3></div><button className="button small" onClick={() => setProperty({ ...blankProperty })}><Plus size={18}/>Add property</button></div><Notice>Saved notes help with future requests. To change access instructions for already scheduled work, send the team a message too.</Notice><div className="spacer"/>{!properties.length ? <Empty title="Tell us about your home." action={<button className="button outline" onClick={() => setProperty({ ...blankProperty })}>Save a property</button>}>Save your address, gate details and access notes for your next quote request.</Empty> : <div className="customer-property-grid">{properties.map((item: any) => { const propertyJobs = jobs.filter((job: any) => String(job.address).trim().toLowerCase() === String(item.address).trim().toLowerCase()); const done = propertyJobs.filter((job: any) => job.status === 'completed'); return <article className="white-card customer-passport" key={item.id}><div className="customer-property-top"><House size={32}/><span className="customer-kicker">PROPERTY PASSPORT</span></div><h3>{item.label}</h3><p>{item.address}<br/>{item.area}, {item.postal_code}</p><div className="customer-property-stats"><div><strong>{done.length}</strong><span>Completed visits</span></div><div><strong>{propertyJobs.filter((job: any) => ['scheduled', 'in_progress'].includes(job.status)).length}</strong><span>Open visits</span></div></div><div className="customer-property-notes"><strong>Access & care notes</strong><p>{item.details || 'Add gate details, pets, surface concerns or anything that helps us care for your property.'}</p></div><div className="button-row"><button className="button small outline" onClick={() => setProperty({ ...item, postalCode: item.postal_code })}>Edit details</button><a className="button small" href={'/book?property=' + encodeURIComponent(item.id)}>Request care <ArrowUpRight size={17}/></a></div></article>; })}</div>}</TabsContent>

        <TabsContent value="billing"><div className="customer-balance-band"><div><span className="customer-kicker">YOUR OUTSTANDING BALANCE</span><strong>{money(balance / 100)}</strong><p>{openInvoices.length} unpaid invoice{openInvoices.length === 1 ? '' : 's'}{overdue.length ? ` · ${overdue.length} overdue` : ''}</p></div><div><ShieldPayment/><p>Payments appear after Trios verifies receipt. Your bank transfer is not automatically confirmed here.</p></div></div><div className="customer-filter-row">{searchBox('Search invoices or address')}<Pick label="Invoice status" value={billingFilter} onChange={setBillingFilter} options={[{ value: 'all', label: 'All invoices' }, { value: 'open', label: 'Balance outstanding' }, { value: 'overdue', label: 'Overdue' }, { value: 'paid', label: 'Paid in full' }]}/></div>{!filteredInvoices.length ? <Empty title="No invoices in this view.">Itemized invoices and verified payment records will appear here after a quote is accepted.</Empty> : filteredInvoices.map((item: any) => { const remaining = invoiceBalance(item); const total = Number(item.amount_cents) + Number(item.tax_cents); const late = remaining > 0 && item.due_date && item.due_date < today; return <article className="list-card" key={item.id}><div className="list-card-head"><div><h3>Invoice {reference(item.id)}</h3><p className="small-text">{item.description}</p></div><Status value={late ? 'overdue' : item.status}/></div><div className="list-meta"><span><CalendarDays size={17}/>{remaining ? 'Due ' : 'Due date '}{niceDate(item.due_date)}</span><span><MapPin size={17}/>{item.address}</span></div><div className="customer-invoice-totals"><div><span>Invoice total</span><strong>{money(total / 100)}</strong></div><div><span>Verified payments</span><strong>{money(Number(item.paid_cents || 0) / 100)}</strong></div><div><span>Remaining</span><strong>{money(remaining / 100)}</strong></div></div><div className="button-row"><button className="button small" onClick={() => setInvoice(item)}>View invoice & payment details</button><a className="button small outline" href={'/api/invoice/' + item.id}><Download size={17}/>Download</a></div></article>; })}</TabsContent>

        <TabsContent value="changes"><ServiceChanges mode="customer" jobs={jobs} requests={requests} onUpdated={refresh}/></TabsContent>
        <TabsContent value="messages"><div className="customer-message-layout"><section className="white-card"><span className="customer-kicker">YOUR CARE TEAM</span><h3 ref={messageHeading} tabIndex={-1}>How can we help?</h3><p>Send a question or update. Replies appear in your account; messages are not monitored as an emergency service.</p><div className="customer-message-topics">{['Access update', 'Moving plan question', 'Schedule question', 'Invoice question', 'Service feedback'].map(topic => <button type="button" key={topic} onClick={() => setSubject(topic)}>{topic}</button>)}</div><form onSubmit={async event => { event.preventDefault(); if (await mutate({ action: 'message', subject, body }, 'Message sent to Trios')) { setSubject(''); setBody(''); } }}><div className="form-grid"><label className="wide">Subject<input required minLength={2} value={subject} onChange={event => setSubject(event.target.value)} maxLength={150} placeholder="What is your message about?"/></label><label className="wide">Message<textarea required minLength={5} rows={6} value={body} onChange={event => setBody(event.target.value)} maxLength={3000} placeholder="Add the property address, request reference and details we should know."/><span className="customer-character-count">{body.length}/3,000 characters</span></label></div><button className="button full" disabled={saving}>{saving ? 'Sending…' : 'Send message'}<Mail size={18}/></button></form><a className="text-link customer-call" href={'tel:' + CONTACT.tel}>Prefer to talk? {CONTACT.phone}</a></section><section><div className="section-head"><h3>Your conversations</h3><span className="customer-kicker">{messages.length} TOTAL</span></div><div className="customer-filter-row">{searchBox('Search conversations')}<Pick label="Conversation status" value={messageFilter} onChange={setMessageFilter} options={[{ value: 'all', label: 'All conversations' }, { value: 'replied', label: 'With team replies' }, { value: 'waiting', label: 'Awaiting reply' }]}/></div>{!filteredMessages.length ? <Empty title="Your conversations live here.">Send a message and return here to read the team’s response.</Empty> : filteredMessages.map((message: any) => <article className="list-card customer-message" key={message.id}><div className="list-card-head"><h3>{message.subject}</h3><Status value={message.reply ? 'replied' : 'open'}/></div><p>{message.body}</p><span className="small-text muted">Sent {niceDate(message.created_at)}</span>{message.reply && <div className="customer-team-reply"><span className="customer-kicker">TRIOS REPLIED</span><p>{message.reply}</p><button className="text-link" onClick={() => compose(('Follow-up: ' + message.subject).slice(0, 150), `Following up on my message from ${niceDate(message.created_at)}: ${message.subject}\n\n`)}>Send a follow-up <ArrowRight size={17}/></button></div>}</article>)}</section></div></TabsContent>
      </Tabs><CustomerPrivacyNote/>

      <Dialog open={!!property} onOpenChange={open => !open && !saving && setProperty(null)}><DialogContent className="customer-dialog"><DialogTitle>{property?.id ? 'Edit your property passport' : 'Save a property passport'}</DialogTitle><DialogDescription>A reliable record of your address and access needs.</DialogDescription>{property && <form onSubmit={async event => { event.preventDefault(); if (await mutate({ ...property, action: 'property' }, 'Property passport saved')) setProperty(null); }}><div className="form-grid"><label className="wide">Property name<input required minLength={2} maxLength={100} value={property.label} onChange={event => setProperty({ ...property, label: event.target.value })}/></label><label className="wide">Street address<input required minLength={5} maxLength={250} autoComplete="street-address" value={property.address} onChange={event => setProperty({ ...property, address: event.target.value })}/></label><div className="field"><label htmlFor="property-area">Community</label><Pick id="property-area" label="Property community" value={property.area} onChange={value => setProperty({ ...property, area: value })} options={AREAS}/></div><label>Postal code<input required autoComplete="postal-code" pattern="[ABCEGHJ-NPRSTVXYabceghj-nprstvxy][0-9][ABCEGHJ-NPRSTVWXYZabceghj-nprstvwxyz][ -]?[0-9][ABCEGHJ-NPRSTVWXYZabceghj-nprstvwxyz][0-9]" maxLength={7} value={property.postalCode} onChange={event => setProperty({ ...property, postalCode: event.target.value.toUpperCase() })}/></label><label className="wide">Access & care notes<textarea rows={5} maxLength={2000} value={property.details} onChange={event => setProperty({ ...property, details: event.target.value })} placeholder="Gate width, pets, parking, surface concerns, accessibility needs and snow-storage space."/></label></div><p className="small-text muted">Avoid including alarm codes or passwords. Contact Trios to agree on secure access arrangements.</p><button className="button full" disabled={saving}>{saving ? 'Saving…' : 'Save property'}</button></form>}</DialogContent></Dialog>
      <Dialog open={!!quote} onOpenChange={open => !open && !saving && setQuote(null)}><DialogContent className="customer-dialog"><DialogTitle>Your property quote</DialogTitle><DialogDescription>{quote && reference(quote.id)} · {quote?.address}</DialogDescription>{quote && <><div className="customer-quote-total">{money(quote.quote_total / 100)}</div><p className="small-text">Final quote total. Read the full scope and tax treatment below.</p><div className="customer-quote-terms">{quote.quote_terms}</div>{parseDetails(quote.details).moving&&<details className="customer-details"><summary>Review the submitted moving plan</summary><MovingBrief value={parseDetails(quote.details).moving}/><p className="small-text">The written quote above defines the final included scope.</p></details>}{quote.status === 'quoted' ? <><Notice>Accepting confirms your agreement to this quote. Trios will finalize scheduling and the payment arrangements described above.</Notice><button className="button" disabled={saving} onClick={async () => { if (await mutate({ action: 'request_action', id: quote.id, status: 'accepted', quoteVersion: quote.updated_at }, 'Quote accepted. Trios will confirm scheduling.')) setQuote(null); }}>{saving ? 'Accepting…' : 'Accept this quote'}<Check size={18}/></button></> : <Status value="accepted"/>}<a className="button outline" href={'/api/quote/' + quote.id}><Download size={18}/>Download this quote</a></>}</DialogContent></Dialog>
      <AlertDialog open={!!cancel} onOpenChange={open => !open && !saving && setCancel(null)}><AlertDialogContent><AlertDialogTitle>Cancel this quote request?</AlertDialogTitle><AlertDialogDescription>This closes {cancel && reference(cancel.id)}. You can make a new request whenever you are ready. Accepted service arrangements require a conversation with Trios.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={saving}>Keep request</AlertDialogCancel><button className="button" disabled={saving} onClick={async () => { if (await mutate({ action: 'request_action', id: cancel.id, status: 'cancelled' }, 'Request cancelled')) setCancel(null); }}>{saving ? 'Cancelling…' : 'Cancel request'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
      <Dialog open={!!invoice} onOpenChange={open => !open && setInvoice(null)}><DialogContent className="customer-dialog"><DialogTitle>Invoice {invoice && reference(invoice.id)}</DialogTitle><DialogDescription>Trios Snow and Mowing Inc. · {invoice?.address}</DialogDescription>{invoice && <><p>{invoice.description}</p><div className="summary-line"><span>Due date</span><strong>{niceDate(invoice.due_date)}</strong></div><div className="summary-line"><span>Service amount</span><strong>{money(invoice.amount_cents / 100)}</strong></div><div className="summary-line"><span>Applicable tax</span><strong>{money(invoice.tax_cents / 100)}</strong></div><div className="summary-line total"><span>Total</span><strong>{money((Number(invoice.amount_cents) + Number(invoice.tax_cents)) / 100)}</strong></div><div className="summary-line"><span>Verified payments</span><strong>{money(Number(invoice.paid_cents || 0) / 100)}</strong></div><div className="summary-line total"><span>Remaining balance</span><strong>{money(invoiceBalance(invoice) / 100)}</strong></div>{(data.payments || []).filter((payment: any) => payment.invoice_id === invoice.id).map((payment: any) => <div className="summary-line" key={payment.id}><span>{niceDate(payment.received_at)} · {payment.method}<br/>{payment.reference}</span><strong>{money(payment.amount_cents / 100)}</strong></div>)}{invoiceBalance(invoice) > 0 ? <Notice>{data.settings?.paymentInstructions || 'Contact Trios for the payment instructions for this invoice.'} Include invoice reference {reference(invoice.id)}.</Notice> : <Notice>This invoice is paid in full according to the verified payment records.</Notice>}<button className="button outline" onClick={() => copy(reference(invoice.id))}><Copy size={17}/>Copy invoice reference</button><a className="button" href={'/api/invoice/' + invoice.id}><Download size={18}/>Download itemized invoice</a></>}</DialogContent></Dialog>
    </div></>;
}

function ShieldPayment() { return <span className="customer-payment-note"><CheckCircle2 size={20}/>Clear records. Verified payments.</span>; }
function RequestProgress({ request, jobs }: { request: any; jobs: any[] }) {
  if (request.status === 'cancelled') return <p className="customer-progress-note">This request is closed. No further visits are confirmed by this request.</p>;
  const stage = jobs.some(job => ['scheduled', 'in_progress', 'completed'].includes(job.status)) ? 3 : request.status === 'accepted' ? 2 : request.status === 'quoted' ? 1 : 0;
  return <ol className="customer-request-progress" aria-label="Request progress">{['Request received', 'Quote ready', 'Quote accepted', 'Visits arranged'].map((label, index) => <li key={label} data-complete={index <= stage} aria-current={index === stage ? 'step' : undefined}><span>{index < stage ? <Check size={14}/> : index + 1}</span><strong>{label}</strong></li>)}</ol>;
}
function RequestDetails({ request }: { request: any }) { const details = parseDetails(request.details); return <div className="customer-submitted-details">{details.moving&&<MovingBrief value={details.moving}/>}<dl><div><dt>Contact</dt><dd>{request.customer_name} · {request.email}<br/>{request.phone}</dd></div><div><dt>Preferred first visit</dt><dd>{details.preferredDate ? niceDate(details.preferredDate) : 'To be discussed'}</dd></div>{parseList(request.services).includes('snow') && <><div><dt>Winter access</dt><dd>{details.drivewaySize === 'large' ? 'Larger / assessment needed' : `${details.drivewaySize || '1'} driveway category`} · {details.surface || 'Surface to be reviewed'} · {details.slope || 'Slope to be reviewed'}</dd></div><div><dt>Requested extras</dt><dd>{[details.salt && 'Salting', details.walkway && 'Walkways / steps', details.priority && 'Priority availability'].filter(Boolean).join(' · ') || 'No extras selected'}</dd></div><div><dt>Snow placement</dt><dd>{details.snowStorage || 'To be agreed'}</dd></div></>}{details.lawnArea && <div><dt>Lawn / garden area</dt><dd>{details.lawnArea}</dd></div>}<div><dt>Access notes</dt><dd>{details.access || 'No additional notes'}</dd></div></dl>{parseList(details.photos).length > 0 && <div className="photo-thumbs">{parseList(details.photos).map((id, index) => <a key={id} href={'/api/files/' + id} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/files/' + id} alt={'Submitted property photo ' + (index + 1)}/></a>)}</div>}</div>; }
function VisitCard({ job, onMessage }: { job: any; onMessage?: (subject: string, body?: string) => void }) {
  return <article className="list-card customer-visit"><div className="list-card-head"><div><span className="customer-kicker">{reference(job.request_id)}</span><h3>{serviceName(job.service)}</h3><p className="small-text">{job.address}</p></div><Status value={job.status}/></div><div className="customer-visit-window"><CalendarDays size={28}/><div><strong>{niceDate(job.scheduled_date)}</strong><span><Clock size={16}/>{job.time_window || 'Window to be confirmed'} · St. John’s time</span></div></div>{job.crew_name && <p className="small-text">Your team: <strong>{job.crew_name}</strong></p>}{job.notes && <div className="customer-visit-notes"><strong>{job.status === 'completed' ? 'Completion notes' : 'Visit notes'}</strong><p>{job.notes}</p></div>}{parseList(job.photos).length > 0 && <div className="customer-completion-photos"><span className="customer-kicker">YOUR SERVICE PHOTOS</span><div className="photo-thumbs">{parseList(job.photos).map((id, index) => <a key={id} href={'/api/files/' + id} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/files/' + id} alt={'Service completion photograph ' + (index + 1)}/></a>)}</div></div>}{onMessage && <div className="button-row"><button className="button small outline" onClick={() => onMessage((job.status === 'completed' ? 'Service feedback: ' : 'Visit question: ') + reference(job.request_id), `Service: ${serviceName(job.service)}\nProperty: ${job.address}\nVisit: ${niceDate(job.scheduled_date)} · ${job.time_window}\n\n`)}><MessageCircle size={17}/>{job.status === 'completed' ? 'Send service feedback' : 'Ask about this visit'}</button></div>}</article>;
}
