import { ArrowUpRight, Phone, Mail, Snowflake, Leaf, MapPin, Truck } from 'lucide-react';
import { Brand } from './brand';
import { CONTACT } from '@/lib/catalog';

export function Footer() {
  return <footer className="footer brand-footer public-footer">
    <div className="container footer-invitation"><div><div className="eyebrow">A HOME FOR EVERY SEASON</div><h2>Every season.<br /><span>Every new chapter.</span></h2></div><div><p>Bring your property care together.<br />Start with the help you need today.</p><a className="button lime" href="/book">Build your property plan <ArrowUpRight size={23} /></a><a href="/contact" className="public-footer-secondary">Have a question? Talk to Trios <ArrowUpRight size={20} /></a></div></div>
    <div className="container"><div className="footer-grid"><div className="footer-brand"><Brand footer /><p>Snow clearing, lawn care, seasonal essentials and moving help, built around your life.</p><span className="footer-location"><MapPin size={18} />St. John’s, Newfoundland & Labrador</span></div><div><h4>PROPERTY CARE</h4><nav className="footer-links" aria-label="Property care services"><a href="/services/snow">Snow clearing</a><a href="/services/lawn">Lawn & garden</a><a href="/moving">Moving services · four tiers</a><a href="/services/spring">Spring cleanup</a><a href="/services/fall">Fall & leaf cleanup</a><a href="/services">Explore all services</a><a href="/plans">Seasonal plans</a></nav></div><div><h4>YOUR TRIOS</h4><nav className="footer-links" aria-label="Customer resources"><a href="/portal">My property account</a><a href="/planner">Care planner</a><a href="/areas">Service areas</a><a href="/contact">Contact Trios</a><a href="/terms">How requests work</a></nav></div><div className="footer-contact"><h4>LET’S TALK PROPERTY CARE</h4><div className="footer-links"><a className="footer-phone" href={'tel:' + CONTACT.tel}><Phone size={20} />{CONTACT.phone}</a><a href={'mailto:' + CONTACT.email}><Mail size={20} />{CONTACT.email}</a><span>{CONTACT.website}</span></div></div></div><div className="public-footer-seasonal" aria-hidden="true"><Snowflake /><span>SNOW.</span><Leaf /><span>MOW.</span><span className="moving-footer-move"><Truck /><span>MOVE.</span></span></div><div className="footer-bottom"><span className="footer-meta"><span>© {new Date().getFullYear()} Trios Snow and Mowing Inc.</span><span className="footer-credit">Designed and developed by <a href="https://avaloncreative.group" target="_blank" rel="noopener noreferrer" aria-label="Avalon Creative Group (opens in a new tab)">Avalon Creative Group<ArrowUpRight size={16} aria-hidden="true" /></a>.</span></span><div><a href="/privacy">Privacy</a><a href="/terms">Service information</a><span>Prices in CAD</span></div></div></div>
  </footer>;
}
