'use client';
import { Footer } from './site-footer';
import { Brand } from './brand';
import { Home } from './home-page';
import { lazy,Suspense } from 'react';
import { ArrowUpRight,MapPin,Phone,Menu } from 'lucide-react';
import { Sheet,SheetContent,SheetTitle,SheetTrigger } from '@/components/ui/sheet';
import { Toaster } from '@/components/ui/sonner';
import { CONTACT } from '@/lib/catalog';
import { ServiceIcon } from './shared';
const Services=lazy(()=>import('./public-services').then(m=>({default:m.PublicServices})));
const ServiceDetail=lazy(()=>import('./public-services').then(m=>({default:m.PublicServiceDetail})));
const Plans=lazy(()=>import('./public-services').then(m=>({default:m.PublicPlans})));
const Booking=lazy(()=>import('./booking').then(m=>({default:m.Booking})));
const Portal=lazy(()=>import('./portal').then(m=>({default:m.Portal})));
const Planner=lazy(()=>import('./planner').then(m=>({default:m.Planner})));
import { ContactPage,AreasPage,PolicyPage } from './support-pages';
export { Brand } from './brand';
const links=[['Services','/services'],['Seasonal plans','/plans'],['Care planner','/planner'],['Service areas','/areas']];
export function SiteApp({page,serviceId}:{page:string;serviceId?:string}){return <div className={'site site-page-'+page}><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><div className="topbar"><div className="container"><span><MapPin size={13}/>Property care in St. John’s & surrounding communities</span><a className="phone-top" href={'tel:'+CONTACT.tel}><Phone size={13}/>{CONTACT.phone}</a></div></div><div className="site-nav container"><Brand/><nav className="nav-links" aria-label="Main navigation">{links.map(([label,url])=><a className={url==='/'+page?'active':''} aria-current={url==='/'+page?'page':undefined} href={url} key={url}>{label}</a>)}</nav><div className="nav-actions"><a href="/portal" className="text-link portal-link">My property <ArrowUpRight size={15}/></a><a href="/book" className="button">Get a quote <ArrowUpRight size={16}/></a><Sheet><SheetTrigger asChild><button className="mobile-menu" aria-label="Open menu"><Menu size={23}/></button></SheetTrigger><SheetContent className="trios-mobile-drawer" aria-describedby={undefined}><SheetTitle style={{padding:25}}>Explore Trios</SheetTitle><nav className="mobile-links" aria-label="Mobile navigation">{[...links,['My property','/portal'],['Contact us','/contact']].map(([label,url])=><a href={url} key={url}>{label}</a>)}</nav><div className="mobile-drawer-actions"><a className="button full" href="/book">Get a quote <ArrowUpRight size={20}/></a><a className="button outline full" href={'tel:'+CONTACT.tel}><Phone size={20}/>Call Trios</a></div></SheetContent></Sheet></div></div></header><main id="main-content"><Suspense fallback={<div className="container loading">Loading your workspace…</div>}>{page==='home'?<Home/>:page==='services'?<Services/>:page==='service'?<ServiceDetail id={serviceId||''}/>:page==='plans'?<Plans/>:page==='book'?<Booking/>:page==='portal'?<Portal/>:page==='planner'?<Planner/>:page==='contact'?<ContactPage/>:page==='areas'?<AreasPage/>:<PolicyPage page={page}/>}</Suspense></main><Footer/><Toaster position="bottom-right" richColors closeButton/></div>}
export function Intro({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="page-intro container"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{children&&<p>{children}</p>}</div>}
export function ServiceCard({service:s,photo=false}:{service:any;photo?:boolean}){return <article className={"service-card service-card-"+s.id}>{photo&&s.image&&<img className="service-photo" src={s.image} alt={s.name==='Snow clearing'?'A freshly cleared residential driveway':'A tidy lawn and garden'} loading="lazy"/>}<div className="service-card-body"><div className="service-top"><span className="icon-box"><ServiceIcon name={s.icon}/></span><span className="pill">{s.category}</span></div><h3><a href={'/services/'+s.id}>{s.name}</a></h3><p>{s.description}</p><div className="service-bottom"><span>{s.id==='snow'?<><strong>{s.price}</strong> <span className="muted">{s.unit}</span></>:<strong style={{fontSize:'1rem'}}>{s.price}</strong>}</span><a href={'/services/'+s.id} aria-label={'Explore '+s.name} className="icon-box" style={{width:48,height:48,borderRadius:50}}><ArrowUpRight size={17}/></a></div></div></article>}
