export const SERVICES = [
{id:'snow',name:'Snow clearing',category:'Winter',icon:'snow',summary:'A clear driveway. A better start to your day.',description:'Seasonal driveway snowblowing, with walkway clearing, ice treatment and plow-ridge return visits available by request.',includes:['Driveway snowblowing','Agreed snow placement on your property','Completion updates in your account'],scope:'Driveway dimensions, snow-storage space and access are reviewed before confirmation. Snow hauling and roof work are excluded.',price:'From $599',unit:'/ season',frequency:'Seasonal',image:'/winter-hero.webp'},
{id:'lawn',name:'Lawn mowing & edging',category:'Summer',icon:'leaf',summary:'A lawn you love, without losing your weekend.',description:'Scheduled mowing, careful edge trimming and a tidy finish on your paths. Choose weekly or fortnightly visits.',includes:['Lawn mowing','Edge and obstacle trimming','Clippings cleared from paths'],scope:'Pricing depends on lawn area, slope, gates and growth. Pesticide applications are excluded.',price:'Personalized quote',unit:'',frequency:'Weekly or fortnightly',image:'/summer-lawn.webp'},
{id:'spring',name:'Spring yard cleanup',category:'Spring',icon:'sun',summary:'A fresh start for everything outside.',description:'Clear the winter litter, rake the lawn and prepare your garden beds for the growing season.',includes:['Raking and loose winter litter','Small fallen branch collection','Garden bed tidying'],scope:'Materials are bagged or placed on site. Off-site disposal is separately assessed.',price:'Personalized quote',unit:'',frequency:'One-time'},
{id:'fall',name:'Fall & leaf cleanup',category:'Fall',icon:'wind',summary:'Put your garden to bed for winter.',description:'Leaf collection, a final lawn tidy and seasonal garden cleanup, in one visit or a scheduled series.',includes:['Leaf raking and collection','Final mowing by agreement','Seasonal garden bed cleanup'],scope:'No large tree work or hazardous waste. Waste removal must be included in the confirmed scope.',price:'Personalized quote',unit:'',frequency:'One-time or recurring'},
{id:'garden',name:'Garden maintenance',category:'Summer',icon:'flower',summary:'A little attention. A whole lot of growth.',description:'Hand weeding, flower planting, mulch spreading and watering tailored to your garden.',includes:['Manual weeding','Planting and mulching','Watering by arrangement'],scope:'Plants and materials quoted separately. No herbicides, pesticides or weed-and-feed treatments.',price:'Personalized quote',unit:'',frequency:'Monthly'},
{id:'aeration',name:'Aeration & overseeding',category:'Spring',icon:'sprout',summary:'Give your lawn room to breathe.',description:'Seasonal soil aeration and grass overseeding, timed around suitable growing conditions.',includes:['Lawn assessment','Core aeration','Grass seed application by agreement'],scope:'Underground services and irrigation must be identified. Seed and materials included only when quoted.',price:'Personalized quote',unit:'',frequency:'Seasonal'},
{id:'hedges',name:'Hedge & shrub shaping',category:'Summer',icon:'scissors',summary:'Clean lines for your outdoor spaces.',description:'Careful shaping of small hedges and shrubs accessible from the ground.',includes:['Ground-level hedge trimming','Small shrub shaping','On-site clipping collection'],scope:'Tree felling, climbing, work near power lines and elevated work are excluded.',price:'Personalized quote',unit:'',frequency:'Seasonal'},
{id:'walkways',name:'Walkways & entrances',category:'Winter',icon:'footprints',summary:'Care for the path to your front door.',description:'Snow clearing for agreed steps, entrance paths and access to garbage storage areas.',includes:['Entrance path clearing','Agreed step clearing','Access-area photos after service'],scope:'Ice treatment is optional. Access, handrails and surface condition are assessed.',price:'Personalized quote',unit:'',frequency:'Seasonal or per visit'},
{id:'ice',name:'Salting & sanding',category:'Winter',icon:'droplets',summary:'Extra attention when surfaces freeze.',description:'Ice-control treatment for agreed walking and driving surfaces, with material application recorded.',includes:['Agreed surface treatment','Material and time record','Follow-up needs flagged'],scope:'Treatment reduces risk but cannot guarantee ice-free surfaces. Refreezing may need repeat treatment.',price:'Add to your snow plan',unit:'',frequency:'As needed'},
{id:'windrow',name:'Plow-ridge return visits',category:'Winter',icon:'truck',summary:'Reopen the end of your driveway.',description:'A return visit to remove the ridge left at your driveway entrance after municipal plowing.',includes:['Driveway entrance reopening','Agreed snow placement','Return-visit completion update'],scope:'Subject to route capacity and confirmed visit terms; municipal plow timing is outside our control.',price:'Personalized quote',unit:'',frequency:'As needed'},
{id:'bins',name:'Bin set-out & return',category:'Year-round',icon:'recycle',summary:'Collection day, taken care of.',description:'Your bins moved to the agreed collection point and returned to their storage area.',includes:['Scheduled bin set-out','Return after collection','Missed-collection issues reported'],scope:'Contents must comply with local collection rules. This service does not include hauling waste.',price:'Personalized quote',unit:'',frequency:'Weekly'},
{id:'furniture',name:'Patio setup & pack-away',category:'Fall',icon:'armchair',summary:'Make room for the next season.',description:'Move outdoor furniture, planters and accessories into or out of your own storage.',includes:['Furniture setup or pack-away','Agreed on-property moving','Space left tidy'],scope:'Heavy or fragile items need assessment. No electrical installation or structural work.',price:'Personalized quote',unit:'',frequency:'Seasonal'},
{id:'cleaning',name:'Home & rental cleaning',category:'Year-round',icon:'sparkles',summary:'A fresh space for you or your next guest.',description:'Routine home cleaning and rental turnovers, with linen changes and restocking by arrangement.',includes:['Agreed room-by-room cleaning','Optional linen changes','Restocking checklist'],scope:'Availability is confirmed by assessment. No biohazard, mould or specialist remediation.',price:'Personalized quote',unit:'',frequency:'One-time or recurring'},
{id:'washing',name:'Exterior & pressure washing',category:'Summer',icon:'droplets',summary:'Refresh your hard outdoor surfaces.',description:'Request an assessment for suitable patios, paths and exterior surfaces.',includes:['Surface and access assessment','Agreed cleaning area','Runoff approach reviewed'],scope:'Assessment required before booking. Delicate siding, roofs, wastewater and property damage risks are reviewed.',price:'Assessment required',unit:'',frequency:'By assessment'},
{id:'windows',name:'Ground-access window cleaning',category:'Summer',icon:'sun',summary:'A clearer view from home.',description:'Exterior window cleaning where windows can be safely reached from the ground.',includes:['Ground-access assessment','Agreed exterior panes','Finish check'],scope:'No roof access or elevated ladder work. Availability and scope are confirmed first.',price:'Assessment required',unit:'',frequency:'By assessment'},
{id:'gutters',name:'Gutter cleaning assessment',category:'Fall',icon:'home',summary:'Plan ahead for falling leaves.',description:'Request an assessment of gutter-cleaning access and the appropriate method or specialist referral.',includes:['Access and scope review','Written recommendation','Quote or referral where appropriate'],scope:'Elevated work requires appropriate equipment and coverage. A request is not an accepted service booking.',price:'Assessment required',unit:'',frequency:'By assessment'},
{id:'hauling',name:'Yard waste removal assessment',category:'Year-round',icon:'truck',summary:'An agreed plan for collected yard waste.',description:'Request a separate quote for eligible nonhazardous yard material and disposal.',includes:['Material and volume review','Disposal fees in quote','Approved disposal arrangements'],scope:'Commercial disposal permits must be in place. No hazardous waste, asbestos, chemicals or contaminated material.',price:'Assessment required',unit:'',frequency:'By assessment'},
];
export const CONTACT={phone:'+1 (709) 470 0727',tel:'+17094700727',email:'triossnow@gmail.com',website:'www.triosservices.ca'};
export const SEASON='December 15, 2026 – April 15, 2027';
export const AREAS=['St. John’s','Mount Pearl','Paradise','Portugal Cove–St. Philip’s','Torbay','Other / request assessment'];
export function snowEstimate(size:string,salt:boolean){if(salt&&size==='3')return null;return size==='1'?(salt?699:599):size==='2'?(salt?899:750):size==='3'?850:null}
export const money=(value:number|string)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(Number(value));
export function niceDate(value:string){if(!value)return 'To be scheduled';return new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',year:'numeric',timeZone:'America/St_Johns'}).format(new Date(value.length===10?value+'T12:00:00Z':value))}
export const faqs=[['When does the winter season run?',`The 2026–27 winter service period is ${SEASON}. Any service outside those dates needs a separate agreement.`],['Is my quote a confirmed booking?','Your request is saved immediately. Trios reviews property details, scope and route capacity, then issues a final quote. A service is confirmed after the quote is accepted and any agreed payment arrangements are completed.'],['Can I request early-morning priority?','Yes. Tell us your preferred departure time and access needs. Priority availability is reviewed against route capacity, and the response window is set out in your final agreement.'],['What happens during a long storm?','The final agreement defines the snowfall trigger, response window and repeat visits. Ongoing snowfall, drifting and unsafe conditions can change the schedule. Check your customer account for updates.'],['Do I need to move my car?','Please provide clear access to the agreed work area. Include parked cars, gates, surface issues and preferred snow-storage areas in your property notes.'],['Can I combine snow and lawn services?','Yes. Request Four-Season Care to combine winter clearing, growing-season mowing and spring/fall cleanup. The plan is quoted for your property and visit schedule.'],['Do you offer pesticide treatments or construction work?','Our routine garden services use manual maintenance. Pesticides, electrical work, plumbing, roof work and construction are outside the standard service scope.'],['How do payments work?','You receive an itemized invoice after scope and pricing are agreed. E-transfer payment instructions are provided with the invoice. Payment is recorded only after Trios verifies receipt.']];
