import { identity,sql,noCache,fail } from '@/lib/server';
import { money,niceDate,CONTACT } from '@/lib/catalog';
import { loadSettings,linkCustomer } from '@/lib/operations-server';
import { documentHtml,escapeHtml as e } from '@/lib/documents';
export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){try{
 const user=await identity();if(!user)return new Response('Sign in required',{status:401,headers:noCache});if(!user.owner)await linkCustomer(user);const {id}=await params;
 const i=await sql().prepare('SELECT i.*,r.customer_name,r.address,r.email,r.quote_terms FROM invoices i JOIN requests r ON r.id=i.request_id WHERE i.id=?').bind(id).first();if(!i||(!user.owner&&i.user_id!==user.id))return new Response('Not found',{status:404,headers:noCache});
 const {results:payments}=await sql().prepare('SELECT * FROM payments WHERE invoice_id=? ORDER BY created_at').bind(id).all();const paid=payments.reduce((a:number,p:any)=>a+p.amount_cents,0),total=i.amount_cents+i.tax_cents,settings=await loadSettings();const ref='TR-'+id.slice(0,8).toUpperCase();
 const content=documentHtml('Trios invoice '+ref,`<header><strong>TRIOS SNOW AND MOWING INC.</strong><h1>Invoice ${ref}</h1><p>${e(CONTACT.email)} · ${e(CONTACT.phone)}</p></header><h2>Bill to ${e(i.customer_name)}</h2><p>${e(i.address)}<br>${e(i.email)}</p><p>Issued ${e(niceDate(i.created_at))} · Due ${e(niceDate(i.due_date))}<br>Status: <strong>${e(i.status.toUpperCase())}</strong></p><table><thead><tr><th>Description</th><th>CAD</th></tr></thead><tbody><tr><td>${e(i.description)}</td><td>${money(i.amount_cents/100)}</td></tr><tr><td>Applicable tax</td><td>${money(i.tax_cents/100)}</td></tr><tr><td>Total</td><td>${money(total/100)}</td></tr><tr><td>Payments received</td><td>${money(paid/100)}</td></tr><tr class="total"><td>Balance remaining</td><td>${money((total-paid)/100)}</td></tr></tbody></table>${payments.length?`<h2>Verified payment history</h2><table><thead><tr><th>Date / reference</th><th>Method</th><th>CAD</th></tr></thead><tbody>${payments.map((p:any)=>`<tr><td>${e(niceDate(p.received_at))}<br>${e(p.reference)}</td><td>${e(p.method)}</td><td>${money(p.amount_cents/100)}</td></tr>`).join('')}</tbody></table>`:''}${total>paid?`<h2>Payment instructions</h2><div class="terms">${e(settings.paymentInstructions)}</div><p>Include reference ${ref} with your payment.</p>`:'<p>Thank you. This invoice has been paid in full.</p>'}<h2>Accepted scope and terms</h2><div class="terms">${e(i.quote_terms)}</div><p class="muted">Trios Snow and Mowing Inc. · St. John’s, NL · ${e(CONTACT.website)}</p>`);
 return new Response(content,{headers:{...noCache,'Content-Type':'text/html; charset=utf-8','Content-Disposition':`attachment; filename="Trios-Invoice-${ref}.html"`,'X-Content-Type-Options':'nosniff'}});
 }catch(error){return fail(error)}}
