import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const properties=sqliteTable('properties',{id:text('id').primaryKey(),userId:text('user_id').notNull(),label:text('label').notNull(),address:text('address').notNull(),area:text('area').notNull(),postalCode:text('postal_code').notNull(),details:text('details').notNull().default('{}'),createdAt:text('created_at').notNull()},t=>[index('properties_user').on(t.userId)]);
export const requests=sqliteTable('requests',{id:text('id').primaryKey(),userId:text('user_id').notNull(),customerName:text('customer_name').notNull(),email:text('email').notNull(),phone:text('phone').notNull(),address:text('address').notNull(),area:text('area').notNull(),postalCode:text('postal_code').notNull(),services:text('services').notNull(),frequency:text('frequency').notNull(),details:text('details').notNull(),estimate:integer('estimate'),status:text('status').notNull().default('requested'),quoteTotal:integer('quote_total'),quoteTerms:text('quote_terms'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('requests_user_created').on(t.userId,t.createdAt),index('requests_status').on(t.status)]);
export const crew=sqliteTable('crew',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),phone:text('phone').notNull().default(''),area:text('area').notNull().default('St. John’s'),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull()},t=>[uniqueIndex('crew_email').on(t.email)]);
export const jobs=sqliteTable('jobs',{version:integer('version').notNull().default(0),id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>requests.id),userId:text('user_id').notNull(),service:text('service').notNull(),scheduledDate:text('scheduled_date').notNull(),timeWindow:text('time_window').notNull(),crewId:text('crew_id').references(()=>crew.id),priority:text('priority').notNull().default('Standard'),status:text('status').notNull().default('scheduled'),notes:text('notes').notNull().default(''),photos:text('photos').notNull().default('[]'),labourMinutes:integer('labour_minutes').notNull().default(0),costCents:integer('cost_cents').notNull().default(0),createdAt:text('created_at').notNull(),completedAt:text('completed_at')},t=>[index('jobs_user_date').on(t.userId,t.scheduledDate),index('jobs_crew_date').on(t.crewId,t.scheduledDate)]);
export const invoices=sqliteTable('invoices',{id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>requests.id),userId:text('user_id').notNull(),description:text('description').notNull(),amountCents:integer('amount_cents').notNull(),taxCents:integer('tax_cents').notNull().default(0),dueDate:text('due_date').notNull(),status:text('status').notNull().default('open'),reference:text('reference').notNull().default(''),paidAt:text('paid_at'),createdAt:text('created_at').notNull()},t=>[index('invoices_user').on(t.userId),uniqueIndex('invoice_request').on(t.requestId)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),userId:text('user_id').notNull(),email:text('email').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),reply:text('reply').notNull().default(''),status:text('status').notNull().default('open'),createdAt:text('created_at').notNull()},t=>[index('messages_user').on(t.userId)]);
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),createdAt:text('created_at').notNull()},t=>[index('uploads_user').on(t.userId)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),userId:text('user_id').notNull(),requestId:text('request_id').notNull(),kind:text('kind').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('events_user_date').on(t.userId,t.createdAt)]);
export const equipment=sqliteTable('equipment',{id:text('id').primaryKey(),name:text('name').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),nextService:text('next_service').notNull().default(''),notes:text('notes').notNull().default(''),createdAt:text('created_at').notNull()});

export const contacts=sqliteTable('contacts',{id:text('id').primaryKey(),userId:text('user_id'),name:text('name').notNull(),email:text('email').notNull(),phone:text('phone').notNull(),notes:text('notes').notNull().default(''),createdAt:text('created_at').notNull()},t=>[uniqueIndex('contacts_email').on(t.email)]);
export const commands=sqliteTable('commands',{id:text('id').primaryKey(),action:text('action').notNull(),fingerprint:text('fingerprint').notNull(),createdAt:text('created_at').notNull()});
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),amountCents:integer('amount_cents').notNull(),method:text('method').notNull(),reference:text('reference').notNull(),receivedAt:text('received_at').notNull(),recordedBy:text('recorded_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('payments_invoice').on(t.invoiceId)]);
export const approvals=sqliteTable('approvals',{quoteVersion:text('quote_version').notNull().default(''),id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>requests.id),signer:text('signer').notNull(),method:text('method').notNull(),evidence:text('evidence').notNull(),quoteTotal:integer('quote_total').notNull(),quoteTerms:text('quote_terms').notNull(),recordedBy:text('recorded_by').notNull(),createdAt:text('created_at').notNull()});
export const settings=sqliteTable('business_settings',{id:text('id').primaryKey(),value:text('value').notNull(),updatedAt:text('updated_at').notNull()});
export const plannerUsage=sqliteTable('planner_usage',{id:text('id').primaryKey(),count:integer('count').notNull().default(0)});
