import { cleanMoving, MOVING_TIERS } from '@/lib/moving';
import { identity,sql,noCache,fail } from '@/lib/server';
function csv(v:any){let s=String(v??'');if(/^[\s]*[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
export async function GET(req:Request){try{const u=await identity();if(!u?.owner)return new Response('Owner access required',{status:403,headers:noCache});const type=new URL(req.url).searchParams.get('type')||'invoices';let lines:any[][];
 if(type==='customers'){const {results}=await sql().prepare('SELECT customer_name,email,phone,address,area,postal_code,status FROM requests ORDER BY email,created_at DESC').all();lines=[['Customer','Email','Phone','Property','Community','Postal code','Request status'],...results.map((r:any)=>[r.customer_name,r.email,r.phone,r.address,r.area,r.postal_code,r.status])]}
 else if(type==='jobs'){const {results}=await sql().prepare('SELECT j.*,r.customer_name,r.address,c.name AS crew_name FROM jobs j JOIN requests r ON r.id=j.request_id LEFT JOIN crew c ON c.id=j.crew_id ORDER BY j.scheduled_date').all();lines=[['Visit','Customer','Address','Service','Date','Window','Crew','Status','Minutes','Cost CAD'],...results.map((r:any)=>[r.id,r.customer_name,r.address,r.service,r.scheduled_date,r.time_window,r.crew_name,r.status,r.labour_minutes,r.cost_cents/100])]}
 else if(type==='moves'){const {results}=await sql().prepare("SELECT j.*,r.customer_name,r.address,r.details,c.name AS crew_name,m.stage,m.transport_plan,m.updated_at AS move_updated FROM jobs j JOIN requests r ON r.id=j.request_id LEFT JOIN crew c ON c.id=j.crew_id LEFT JOIN move_runs m ON m.job_id=j.id WHERE j.service='moving' ORDER BY j.scheduled_date").all();lines=[['Move','Customer','Collection','Destination','Tier','Date','Window','Crew','Visit status','Move stage','Listed items','Estimated boxes','Transport plan','Last move update'],...results.map((r:any)=>{const m=cleanMoving(JSON.parse(r.details||'{}').moving);return [r.id,r.customer_name,r.address,m.destination.address,MOVING_TIERS.find(t=>t.id===m.tier)?.name||'',r.scheduled_date,r.time_window,r.crew_name,r.status,r.stage||'planning',m.inventory.reduce((sum,i)=>sum+i.quantity,0),m.boxCount,r.transport_plan,r.move_updated]})]}
 else if(type==='invoices'){const {results}=await sql().prepare('SELECT i.*,r.customer_name,r.address,COALESCE((SELECT SUM(amount_cents) FROM payments WHERE invoice_id=i.id),0) AS paid FROM invoices i JOIN requests r ON r.id=i.request_id ORDER BY i.created_at DESC').all();lines=[['Invoice','Customer','Address','Amount CAD','Tax CAD','Total CAD','Received CAD','Balance CAD','Status','Due date','Paid date','Reference'],...results.map((r:any)=>[r.id,r.customer_name,r.address,r.amount_cents/100,r.tax_cents/100,(r.amount_cents+r.tax_cents)/100,r.paid/100,(r.amount_cents+r.tax_cents-r.paid)/100,r.status,r.due_date,r.paid_at,r.reference])]}
 else return new Response('Unknown export',{status:400,headers:noCache});
 return new Response('\uFEFF'+lines.map(l=>l.map(csv).join(',')).join('\r\n'),{headers:{...noCache,'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="Trios-${type}.csv"`}})}catch(e){return fail(e)}}
